### ISSUE TITLE
[Feature Request] keep it consistent with Optional Config

### ISSUE THREAD

**Issue by zpc7** [Zhengqbbb/cz-git#11]
### 💭 Describe the feature

When I complete `Select the type of change`, I can see that the option `Denote the SCOPE of this change` is an optional option, but if I don't want to set this item, I have to select `empty` with the arrow keys. 

![image](https://user-images.githubusercontent.com/15316908/163671819-3496203e-6835-4e04-806e-88c0fe8cea67.png)

And, Why not keep it consistent with the option `Provide a LONGER description of the change (optional)`, if you type `Enter`, you can skip this optional item directly

In addition, why are these two options for the following item? It is recommended to keep the same behavior as `Provide a LONGER description of the change (optional)`

![image](https://user-images.githubusercontent.com/15316908/163672082-6e5e7b2b-da47-4ce2-a744-8fa03a73377b.png)

**Comment by Zhengqbbb** [comment]
>

**Comment by Zhengqbbb** [comment]
> And, Why not keep it consistent with the option `Provide a LONGER description of the change (optional)`, if you type `Enter`, you can skip this optional item directly
> 
> In addition, why are these two options for the following item? It is recommended to keep the same behavior as `Provide a LONGER description of the change (optional)`

Hi @zpc7 , Thanks for your feedback, but I still don't understand your needs.
Do you mean typing Enter to skip the option, or do you mean you don't want this to appear?

**Comment by Zhengqbbb** [comment]
My design at the time. First of all these two options, one is to skip, the other is to customize. You can rename or change the location to suit your habits.

#### 1. typing Enter to skip the option( “empty”  place upper layer) => use `customScopesAlign` [option](https://cz-git.qbenben.com/guide/options-show.html#customscopesalign)
Change global configuration (~/.czrc)
```json
{ 
    "path": "cz-git",
    "customScopesAlign": "top"
}
```
<img width="1141" alt="wecom-temp-d3ca98bed657bdae515850c799fedb64" src="https://user-images.githubusercontent.com/40693636/163682419-22bd2604-281f-46f3-8652-2f13901c1881.png">

#### 2. you don't want this to appear ( skip questions ) => use `skipQuestions ` [option](https://cz-git.qbenben.com/guide/option-engineer.html#skipquestions)
Also take the global configuration as an example, change the global configuration (~/.czrc)
```json
{ 
    "path": "cz-git",
    "skipQuestions": "footerPrefix"
}
```
<img width="1097" alt="wecom-temp-95a48c483d932496dc91e246def81cdd" src="https://user-images.githubusercontent.com/40693636/163682548-1b813be3-d2c3-432d-b32a-ca44ebfd58eb.png">

> Questions you don't want to appear are skipped

**Comment by zpc7** [comment]
HI @Zhengqbbb , Thank you for your reply.
My preference is to **keep the interaction consistent** when asking for options.
As you can see, when going to `Provide a LONGER description of the change (optional). Use "|" to break new line:`, we can skip this option directly by `Enter`, or Enter something else to complete this option (instead of choosing skip(or Empty) or custom first)

**Comment by Zhengqbbb** [comment]
>  My preference is to **keep the interaction consistent** 

okay, I get it.
Sorry to make you feel the inconsistency in the interaction, but if you ask me which of the two options is a better interaction, I choose the search option.
For engineering projects, these two interactions are designed to reduce repetitive input. If you want to enter, just skip it. You can choose to place the upper layer

e.g: => [.commitlintrc.js](https://github.com/Renovamen/vuepress-theme-gungnir/blob/main/.commitlintrc.js)
![a](https://user-images.githubusercontent.com/40693636/163704055-7416864a-abdf-4a6e-8b14-2c5ef6237f11.gif)
![b](https://user-images.githubusercontent.com/40693636/163704059-820f59b1-f789-4e79-9ca7-6a966527fe0c.gif)
