### ISSUE TITLE
[Feature Request]  Support for issue custom links

### ISSUE THREAD

**Issue by laterdayi** [Zhengqbbb/cz-git#110]
### 💭 Describe the feature

Support for issue custom links, Or provider transformation function

example:

 #31  > https://redmine.com/issues/31

### 💡 Proposed Solution

Support for issue custom links, Or provider transformation function

example:

 #31  > https://redmine.com/issues/31
 #31  > http://192.168.0.1:8000/zentao/bug-view-31.html

**Comment by laterdayi** [comment]
In this way, you can submit the link and click directly to go to the corresponding link

**Comment by Zhengqbbb** [comment]
https://cz-git.qbb.sh/config/engineer#formatmessagecb
https://cz-git.qbb.sh/recipes/default-issues

**Comment by laterdayi** [comment]
@Zhengqbbb  

Thank you very much for your help, but formatMessageCB defaultMessage return is a string. How do I convert defaultMessage to something like a linked text in markdown

#6776 #676  to  [#6776](https://redmine.com/issues/676)

**Comment by laterdayi** [comment]
thank you

**Comment by Zhengqbbb** [comment]
what ever you want message just to custom javascript and do it 🚀

**Comment by Zhengqbbb** [comment]
If you want to play more. Can see #104

**Comment by laterdayi** [comment]
@Zhengqbbb  

May I ask a question? I have changed my formatMessageCB to the desired format, but markdown link does not appear normally in the description. Do you know why?

[Google](https://www.google.com/)  Is displayed as text

![图片](https://user-images.githubusercontent.com/122137647/226854032-db04bece-3eb1-44f4-ab1e-72c4ac3d01b1.png)

**Comment by Zhengqbbb** [comment]
I don't know, it has to do with the display of the hosting platform (Github) support
