### ISSUE TITLE
[Feature Request]  Set scope as a direct input item

### ISSUE THREAD

**Issue by laterdayi** [Zhengqbbb/cz-git#113]
### 💭 Describe the feature

Set scope as a direct input item

ref https://github.com/Zhengqbbb/cz-git/issues/109

### 💡 Proposed Solution

Set scope as a direct input item

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.7.0)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. 🎉

https://cz-git.qbb.sh/recipes/#input-mode
