### ISSUE TITLE
[Bug report] 通过shelljs exec git cz 时 ，输出内容时无法被选中

### ISSUE THREAD

**Issue by laterdayi** [Zhengqbbb/cz-git#117]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
windows
```

#### Expected behavior

通过shelljs exec git cz 时 ，输出内容时无法被选中

const child = exec('git-cz' { async: true});

内容出现但是无法选择

**Comment by Zhengqbbb** [comment]
cz-git是 commitizen cli 的适配器也就是插件

**Comment by laterdayi** [comment]
https://github.com/shelljs/shelljs/wiki/FAQ#running-interactive-programs-with-exec  我意识到可能是shelljs的问题
