### ISSUE TITLE
[Feature Request]  support  bump & Automatic update log generation

### ISSUE THREAD

**Issue by laterdayi** [Zhengqbbb/cz-git#118]
### 💭 Describe the feature

https://commitizen-tools.github.io/commitizen/bump/

**Comment by Zhengqbbb** [comment]
## how to bump and gen changelog is user to choose npm package.
This is python package. python env your can choose it.
But npm env have so many package you can choose.
cz-git just a  follow Conventional Commits rule's `git commit` CLI

## There are pkg you can choose
### About bump:
bumpp: https://www.npmjs.com/package/bumpp

### About changelog:
changset: https://www.npmjs.com/package/@changesets/cli
changelogen: https://github.com/unjs/changelogen
conventional-changelog-cli: https://www.npmjs.com/package/conventional-changelog-cli
changelogithub: https://github.com/antfu/changelogithub
