### ISSUE TITLE
[Feature Request] Set default issue prefix without prompt

### ISSUE THREAD

**Issue by jaklan** [Zhengqbbb/cz-git#12]
### 💭 Describe the feature

I would like to set the default issue prefix: `Issues:`. At the moment I can achieve that with:
```
    prompt: {
        issuePrefixs: [{ value: "Issues:", name: "default" }],
        customIssuePrefixsAlign: "bottom",
    }
```
but I would be anyway prompted to choose the ISSUES type.

I tried changing `emptyIssuePrefixsAlias` and `customIssuePrefixsAlias` to `""`, but with no effect. 

I also tried `skipQuestions: ["footerPrefix"]`, but then there's no prefix used at all.

### 💡 Proposed Solution

Additional boolean options similar to the `Scopes` one: `allowCustomIssuePrefixs` and `allowEmptyIssuePrefixs` and no prompt when there's only one `issuePrefixs` configured.

**Comment by Zhengqbbb** [comment]
@jaklan Thanks for suggestion! 

> but I would be anyway prompted to choose the ISSUES type.

> Additional boolean options similar to the Scopes one: allowCustomIssuePrefixs and allowEmptyIssuePrefixs and no prompt when there's only one issuePrefixs configured.

My understanding is that you don't want `empty` and `custom` in the prompt. Is that so? 🤔

**Comment by Zhengqbbb** [comment]
If that's the case, my design thinking at the time was that it felt **too forced**.
For example, the user has five commits that he wants to associate, but one does not want to associate, (such as modifying the configuration), so he has to associate. I don't know. lol 🤗 ~ But as a configuration I think I can try it, after all, it's a user's choice.
I will follow up over the weekend ~ 💪

**Comment by jaklan** [comment]
Hi @Zhengqbbb,

>My understanding is that you don't want empty and custom in the prompt. Is that so? 🤔

Yeah, exactly that's the case.

> But as a configuration I think I can try it, after all, it's a user's choice.

It's related to the rule in our repository that **each** commit has to be related to the existing issue (which means we create issues even for minor docs or style fixes). Yeah, it's quite "strict" approach, that's why I fully agree `empty` and `custom` should be there by default, but at the same time we would be really grateful to be able to disable them as options - that's the last thing we miss in your awesome adapter in comparison to `cz-customizable` 😊 

Btw, I can easily imagine the case when the issue footer is optional in general, but it should follow some convention if applied, so that change would also resolve that scenario.

**Comment by Zhengqbbb** [comment]
The latest version 🌟(**v1.2.4**)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. Thanks for reporting it! 🎉

**Comment by jaklan** [comment]
@Zhengqbbb unfortunately, also there are some problems with this one:
```js
    allowEmptyIssuePrefixs: false,
    issuePrefixs: [{ value: "Issues:", name: "default" }],
```
generates:
```console
? Select the ISSUES type of change: (Use arrow keys or type to search)
❯ skip 
  custom 
  ──────────────
  default 
```
and
```js
    allowEmptyIssuePrefixs: false,
    allowCustomIssuePrefixs: false,
    issuePrefixs: [{ value: "Issues:", name: "default" }],
```
generates:
```console
? Select the ISSUES type of change: (Use arrow keys or type to search)
❯ skip 
  ──────────────
  default 
```
so `allowEmptyIssuePrefixs` just seems not to work at all.

As I can quickly see - it's again related to problems with the implementation of `filterCustomEmptyByOption` function, probably due to the same reason I described here: https://github.com/Zhengqbbb/cz-git/issues/15#issuecomment-1107451651.

**Comment by Zhengqbbb** [comment]
@jaklan Got it
The latest version 🌟(v1.2.5)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. Thanks for reporting it! 🎉

**Comment by jaklan** [comment]
@Zhengqbbb also works! Just one more thing:
```js
    allowEmptyIssuePrefixs: false,
    allowCustomIssuePrefixs: false,
```
gives:
```console
? Select the ISSUES PREFIX: (Use arrow keys or type to search)
  ──────────────
❯ default 
```
It would be nice to be able to select the only existing option by default, without prompt, which is redundant in such case.

**Comment by jaklan** [comment]
Tested the above in practice recently and already a few people were confused with:
```console
? Select the ISSUES PREFIX: (Use arrow keys or type to search)
  ──────────────
❯ default 
```
and tried to specify issues in that step, so definitely any solution to skip that prompt if there's only one existing prefix would be really helpful.

**Comment by Zhengqbbb** [comment]
Got it！Thank you for your promotion and other people's feedback. ❤️Recently, the project is being refactored. It needs to be merged in advance🧐🤔. The next version will support it.

**Comment by jaklan** [comment]
@Zhengqbbb great to hear! Thanks for all your support, `cz-git` is really a game-changer for `commitizen` adoption in custom setups (we use it in monorepo with ~100 devs!), especially when `cz-customizable` is not maintained for 2 years ❤️

**Comment by Zhengqbbb** [comment]
>  (we use it in monorepo with ~100 devs!) ❤️ 

Oh, really ! It's is my pleasure !

> so definitely any solution to skip that prompt if there's only one existing prefix would be really helpful.

The latest version 🌟(v1.2.7)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. Thanks for reporting it! 🎉

![a](https://user-images.githubusercontent.com/40693636/165436764-a4c38b11-b266-44a2-80d1-14a1bdec82bd.gif)

**Comment by Zhengqbbb** [comment]
Hey bro, have you tried it? If you have any questions, please let me know in time. I am ready for the next stage of development. @jaklan 😇

**Comment by jaklan** [comment]
@Zhengqbbb I have finally tested that today and I can confirm it works! Just to note - I tested that only for my use-case, I haven't done intensive tests to find out any edge cases yet 😉
