### ISSUE TITLE
Unknown option: 'test:commitizen_path'

### ISSUE THREAD

**Issue by laterdayi** [Zhengqbbb/cz-git#128]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
window
```

#### Concise Description

使用 pnpm build

**Comment by laterdayi** [comment]
使用 pnpm build 时 提示 Unknown option: ':commitizen_path'

**Comment by laterdayi** [comment]
似乎与

```
  "config": {
    "commitizen": {
      "path": "node_modules/cz-git"
    }
  }
```
有关

**Comment by Zhengqbbb** [comment]
这并不是 cz-git 的问题，可能与你 build 命令有冲突，我猜你应该有使用 `npm-run-all`这个库
https://github.com/mysticatea/npm-run-all/issues/201

---

解决方案：
- 项目根目录创建 `.czrc`例子：https://github.com/Zhengqbbb/qbb.sh/blob/main/.czrc

**Comment by Zhengqbbb** [comment]
此 ISSUE 我先 close，如果有其他问题欢迎继续 reopen

**Comment by laterdayi** [comment]
好的， 我已通过创建 .czrc解决了， 感谢
