### ISSUE TITLE
[Bug report] 使用Emoje配置模板，commitlint 无法找到 commitlint.config.js 报错

### ISSUE THREAD

**Issue by arronf2e** [Zhengqbbb/cz-git#129]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.06 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  npmPackages:
    commitizen: ^4.3.0 => 4.3.0 
    cz-git: ^1.6.1 => 1.6.1 
  npmGlobalPackages:
    commitizen: 4.3.0
```

#### Screenshots or Screen Recording(if possible)
<img width="1236" alt="image" src="https://github.com/Zhengqbbb/cz-git/assets/15780058/599d327a-2a7d-4a96-965e-63a4650219fa">

**Comment by Zhengqbbb** [comment]
commitlint 验证命令失败与 cz-git 没有关系

使用 `commitlint`  的配置并使用的 `commitlint` CLI 进行验证是要添加至少一个规则的
例如：
```js
rules: {
    'subject-empty': [2, 'never'],
  },
```

如果不想添加 commitlint 规则或使用 commitlint 配置文件

可以使用 `cz.config.js` 与 `cz.config.cjs` 或在package.json 中指定 js 文件
```json
"config": {
    "commitizen": {
      "path": "node_modules/cz-git",
      "czConfig": "./config/cz.config.js"
    }
  }
```
