### ISSUE TITLE
[Feature Request] option for openai base url 

### ISSUE THREAD

**Issue by subframe7536** [Zhengqbbb/cz-git#134]
### 💭 Describe the feature

如题，我使用 https://github.com/justjavac/openai-proxy 部署了自己的服务，希望可以增加替换 base url 的选项

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.7.0)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues.  🎉

```sh
czg --api-endpoint="https://xxxxx.deno.dev/v1"
```
