### ISSUE TITLE
[Feature Request] Support for multiple scopes

### ISSUE THREAD

**Issue by jaklan** [Zhengqbbb/cz-git#14]
### 💭 Describe the feature

`commitlint` provides support for multiple scopes:
https://commitlint.js.org/#/concepts-commit-conventions?id=multiple-scopes

When you use `@commitlint/cz-commitlint` adapter, you can enable support for that in `commitizen` as well by providing the following options in `commitlint` config:
```js
  prompt: {
    settings: {
      enableMultipleScopes: true
      scopeEnumSeparator: ","
    },
  }
```
https://commitlint.js.org/#/reference-prompt?id=settings

Then, you can select multiple scopes in `commitizen` with `space` and confirm with `enter`. If empty scopes are forbidden, if no scope is selected you get the hint you need to select at least one to continue.

### 💡 Proposed Solution

To respect the above configuration. The one issue I see is the fact that in `cz-git` `space` is used as input to `search`, but imho in that case we can "override" its behaviour to select the scope instead - scopes with spaces are rather rare use-case, so imho such a compromise should be quite acceptable. Or we can just think about another keystroke to trigger scope selection / unselection (`right arrow` to select, `left arrow` to unselect?).

**Comment by Zhengqbbb** [comment]
> `commitlint` provides support for multiple scopes: https://commitlint.js.org/#/concepts-commit-conventions?id=multiple-scopes

Yeah ! I checked their source code is done using `inquirer/checkbox`
And we are currently using `inquirer-autocomplete-prompt`.It experience is very nice but currently does not support multiple selection

> Then, you can select multiple scopes in `commitizen` with `space` and confirm with `enter`. If empty scopes are forbidden, if no scope is selected you get the hint you need to select at least one to continue.

If he doesn't choose he can't go to the next question

> 
> ### 💡 Proposed Solution
> To respect the above configuration. The one issue I see is the fact that in `cz-git` `space` is used as input to `search`, but imho in that case we can "override" its behaviour to select the scope instead - scopes with spaces are rather rare use-case, so imho such a compromise should be quite acceptable. Or we can just think about another keystroke to trigger scope selection / unselection (`right arrow` to select, `left arrow` to unselect?).

I think borrowing can be done with `inquirer-checkbox-plus-prompt`, but then I have to write one myself. 🤣

**Comment by jaklan** [comment]
@Zhengqbbb https://github.com/faressoft/inquirer-checkbox-plus-prompt - such library actually already exists 😃

**Comment by Zhengqbbb** [comment]
> @Zhengqbbb https://github.com/faressoft/inquirer-checkbox-plus-prompt - such library actually already exists 😃 (or maybe I just misunderstood your comment about "writing the one myself" 🙈)

LOL, once my own personality starts, I will write all the inquirers myself 🤯.

**Comment by Zhengqbbb** [comment]
Hey bro ! @jaklan 
The latest version 🌟(v1.2.9)🌟 is support for multiple scopes . 💪
- docs: https://cz-git.qbenben.com/guide/recipes.html#support-for-multiple-scopes
- To ensure the search function so I still **add the right arrow as the selected*, and why not choose the left arrow because the left arrow will cause the search character to actually move to the left

![demo](https://user-images.githubusercontent.com/40693636/167989019-8acd8d5a-f47f-44c6-9055-3a8efa0ec2a1.gif)

Now yet I haven't added tests yet to make sure the checkboxes work, I need to add tests later
👀 Please have a try. Let me know if there are still any issues. Thanks for reporting it! 🎉

**Comment by Zhengqbbb** [comment]
@jaklan  Hi, The latest version 🌟(v1.3.1)🌟 
You can enable multiple scopes  mode **without configuration**
Try it !
```bash
checkbox=1 cz
# same it can turn on emoji mode
emoji=1 cz
```

**Comment by jaklan** [comment]
Hello @Zhengqbbb, sorry for a late response, I've finally found some time to test multiple scopes - and they work really nice, thank you!

**Comment by Zhengqbbb** [comment]
> Hello @Zhengqbbb, sorry for a late response, I've finally found some time to test multiple scopes - and they work really nice, thank you!

Great 🤗  Thx u support ~
