### ISSUE TITLE
[Bug report] [err]>>>: Not Found OpenAI API Key, Please use setup command `npx -y czg --api-key="sk-XXXX"`

### ISSUE THREAD

**Issue by sun0225SUN** [Zhengqbbb/cz-git#141]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
[err]>>>: Not Found OpenAI API Key, Please use setup command npx -y czg --api-key="sk-XXXX"
```

### 🔎 Description

不清楚为啥这个 token 设置不成功

![image](https://github.com/Zhengqbbb/cz-git/assets/79169717/1eba4580-6a5a-4b65-ab99-3349dd2fe924)

**Comment by Zhengqbbb** [comment]
Sorry for the trouble~ The previous version has made some changes, but it was not tested in time because the api failed. Thank you for pointing out the problem.

The latest version 🌟(v1.7.1)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. 🎉

**Comment by sun0225SUN** [comment]
thanks

**Comment by Zhengqbbb** [comment]
> thanks

It should be work ~ 👀👀👀

<img width="811" alt="CleanShot 2023-08-08 at 15 22 23@2x" src="https://github.com/Zhengqbbb/cz-git/assets/40693636/c0d43c97-caaf-4390-8e76-f8f20993e9df">
