### ISSUE TITLE
[Feature Request] 非英文字符的自动折行

### ISSUE THREAD

**Issue by violin0622** [Zhengqbbb/cz-git#150]
### 💭 Describe the feature

我使用 `czg` 作为提交工具。
看起来在处理 body 内容输入时， czg 能够进行英文的自动折行，可能是识别了空格？
但是对于汉字内容，没有自动折行，必须在确认提交之前进行二次编辑。

### 💡 Proposed Solution

考虑到在任意两个汉字字符之间折行都不会影响阅读，是否识别汉字的 utf8 编码范围，
直接按行宽折行，而不再寻找空格呢？

**Comment by Zhengqbbb** [comment]
Hi. 处理 body 内容的自动折行是通过 `breaklineNumber ` 控制，默认为为 `100的字符长度`

https://cz-git.qbb.sh/zh/config/engineer#breaklinenumber

![CleanShot 2023-12-12 at 15 12 46@2x](https://github.com/Zhengqbbb/cz-git/assets/40693636/139e48b6-bd99-437c-b84d-7b5c4e3791bd)

---

> 任意两个汉字字符之间折行

英文字符的判断单词不换行通过空格识别是容易实现的，但是中文两个词语不换行这个我没想到有什么好的方法
