### ISSUE TITLE
[Feature Request] Remove extra \n after words.

### ISSUE THREAD

**Issue by SpeedySH** [Zhengqbbb/cz-git#152]
### 💭 Describe the feature

First of all thanks for such a great tool!
The point of the request is that if we in any of the messages (where "|" or any other hyphenation character is allowed), use it at the end, and maybe even in a row, it causes unexpected problems (multiple line breaks).
I'm writing a tool for parsing commits, and this is one of the problems I'm thinking about how to solve, because "foolproofing" should still be included.

### 💡 Proposed Solution

Prohibit the use of line breaks at the beginning of messages and at the end.
Examples:
The input: 
`| || || || | my message |||||||`
should be converted to:
`my message`

The input: 
`| || || || | my message ||||||| my extra message` 
should be converted to:
```
my message
my extra message
```

(No extra line breaks, no extra spaces)

**Comment by Zhengqbbb** [comment]
I appreciate hearing your feedback.
Unfortunately, I won't be handling this request.

This should be the message for the body and BREAKCHANGE.
1. I have performed a simple processing, using `trim()`.
2. You may not want to have too many line breaks. However, some people may have such a requirement, hoping to separate messages with line breaks in the body. As a tool provider, I cannot interfere too much with the message format. 
3. If possible, you can use [formatMessageCB](https://cz-git.qbb.sh/config/engineer#formatmessagecb) for parsing on your own. 

```js
formatMessageCB: ({ defaultHeader, body }) => {
      let res = defaultHeader
      if (body) {
        res += '\n'
        res += body
          .split('\n')
          .map((line) => {
              // do something for line
              return line
          })
          .join('\n')
      }
      return res
    },
```

**Comment by SpeedySH** [comment]
> I appreciate hearing your feedback. Unfortunately, I won't be handling this request.
> 
> This should be the message for the body and BREAKCHANGE.
> 
> 1. I have performed a simple processing, using `trim()`.
> 2. You may not want to have too many line breaks. However, some people may have such a requirement, hoping to separate messages with line breaks in the body. As a tool provider, I cannot interfere too much with the message format.
> 3. If possible, you can use [formatMessageCB](https://cz-git.qbb.sh/config/engineer#formatmessagecb) for parsing on your own.
> 
> ```js
> formatMessageCB: ({ defaultHeader, body }) => {
>       let res = defaultHeader
>       if (body) {
>         res += '\n'
>         res += body
>           .split('\n')
>           .map((line) => {
>               // do something for line like
>              return line === '\n' ? '' : line
>           })
>           .join('\n')
>       }
>       return res
>     },
> ```

Thanks! I close this request
