### ISSUE TITLE
[Feature Request] Ollama integration

### ISSUE THREAD

**Issue by mtompkins** [Zhengqbbb/cz-git#156]
### 💭 Describe the feature

In addition to OpenAI and its associated cost it would be great if we might be able to use [Ollama](https://ollama.ai/)

### 💡 Proposed Solution

Extend the AI integration to use Ollama which allows running various LLM models locally without a fee.

**Comment by Zhengqbbb** [comment]
> 最近，ollama 已实现对 OpenAI 的兼容性。czg 支持 Ollama 一个可行办法是利用 ‘ollama cp’ 命令，将现有模型名复制到一个临时名。在命令行中具体执行像下面这样的命令：

感谢！ 因为电脑容量不够，迟迟没有开始这方面的开发 🫠

**Comment by terranc** [comment]
But every first request fails

**Comment by Zhengqbbb** [comment]
I have released a next pre-release version 🌟(**v1.10.0-beta.1**)🌟 for testing.
Plan for the official release on the weekend  🚀.

**Welcome to try it out! 👀 Let me know if there are still any issues. 🎉**

```sh
npm install -g czg@next
czg -v # ensure version is v1.10.0-beta.1
czg -h # show help

# Usage

### 1. Use the default `gpt-4o-mini` model
czg ai

### 2. Set specify a model in current session
czg ai -M=gpt-3.5-turbo

### 3. Setup the default model
czg --api-model="gpt-4"
```

See more setup details in https://deploy-preview-185--cz-git.netlify.app/recipes/openai#setup-openai-token

**Comment by mtompkins** [comment]
Thanks for your work. I just don't see how this relates to using local LLMs.
I do appreciate the work you do!

**Comment by Zhengqbbb** [comment]
Thank you for testing !

Currently, cz-git and czg only support models compatible with the `/chat/completions` endpoint, but my mac tests or running the Ollama model to generate commit messages have not been effective. 
If someone have any better suggestions, please feel free to share.

![CleanShot 2024-09-26 at 23 20 15@2x](https://github.com/user-attachments/assets/7ae72834-10af-424b-ab19-60136db49d2d)
