### ISSUE TITLE
[Bug report] 使用@commitlint/config-conventional^19出现异常

### ISSUE THREAD

**Issue by BlueCat918** [Zhengqbbb/cz-git#160]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    Memory: 5.86 GB / 15.86 GB
  Binaries:
    Node: 18.19.0
    pnpm: 8.15.4
  npmPackages:
    @commitlint/cli: ^19.0.3
    @commitlint/config-conventional: ^19.0.3
    commitizen: ^4.3.0
    cz-git: ^1.8.0
    vite: ^5.1.4
```

### 🔎 Description

未使用全局配置，使用@commitlint/config-conventional^19的情况下出现以下异常，降级为^18异常消失。

> require() of ES Module ~\node_modules\.pnpm\@commitlint+config-conventional@19.0.3\node_modules\@commitlint\config-conventional\lib\index.js from ~\node_modules\.pnpm\cz-git@1.8.0\node_modules\cz-git\lib\index.js not supported.
> Instead change the require of ~\node_modules\.pnpm\@commitlint+config-conventional@19.0.3\node_modules\@commitlint\config-conventional\lib\index.js in ~\node_modules\.pnpm\cz-git@1.8.0\node_modules\cz-git\lib\index.js to a dynamic import() which is available in all CommonJS modules.

**Comment by Zhengqbbb** [comment]
ref: https://github.com/Zhengqbbb/cz-git/issues/159#issuecomment-1961354215

<img width="1325" alt="image" src="https://github.com/Zhengqbbb/cz-git/assets/40693636/38d7ad11-bd46-4972-a4ca-c443b6cc6c9e">

**Comment by BlueCat918** [comment]
使用的是.commitlintrc.cjs默认配置模板，只添加了extends: ['@commitlint/config-conventional'] 配置项

**Comment by Zhengqbbb** [comment]
> 使用的是.commitlintrc.cjs默认配置模板，只添加了extends: ['@commitlint/config-conventional'] 配置项

能不能提供一个复现仓库

**Comment by Zhengqbbb** [comment]
我已经升级了当前项目的依赖，并发布了预发版本 `1.8.1-beta.3`，已支持加载 `exends` ESM 项目配置
但我仍然需要需要一段时间在其他项目上进行测试后，**预计周末完成升级**

当前你的项目可以使用下面命令进行升级，如果有问题的话，欢迎前来告知 😁

```sh
npm install -D cz-git@next
```

<img width="1022" alt="image" src="https://github.com/Zhengqbbb/cz-git/assets/40693636/6983d002-2e92-4266-9b91-c5829a86133f">

**Comment by Mister-Hope** [comment]
汇报一下，1.8.1-beta.3 在我的项目里没有问题

**Comment by BlueCat918** [comment]
@Zhengqbbb 
升级至 1.8.1-beta.3 问题消失，感谢。

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.9.0)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. 🎉
