### ISSUE TITLE
[Feature Request] Consider making AI fields optional

### ISSUE THREAD

**Issue by recallwei** [Zhengqbbb/cz-git#163]
### 💭 Describe the feature

![image](https://github.com/Zhengqbbb/cz-git/assets/62941121/dda1a90c-e73c-4904-b3b7-7c8b72480195)

If I don't assign these two fields, it will throw a type error.

![image](https://github.com/Zhengqbbb/cz-git/assets/62941121/d1ffc9df-55c1-465c-9e7b-80d954f674e0)

I haven't started using AI yet, and these two fields both have default values.

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.9.1)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. 🎉
