### ISSUE TITLE
[Feature Request] 在选择 scope 的时候允许直接回车跳过而不是选择

### ISSUE THREAD

**Issue by you-hengh** [Zhengqbbb/cz-git#166]
### 💭 Describe the feature

在选择 scope 的时候允许直接回车跳过而不是选择

![image](https://github.com/Zhengqbbb/cz-git/assets/34816426/01f4c36c-b61f-4e11-a8bd-6cf141e43fb6)

如果有内容 就直接写内容 如果内容为空(直接回车)代表忽略 

希望能改成这样的流程,而不是用上下箭头去选择

### 💡 Proposed Solution

上述已截图

**Comment by Zhengqbbb** [comment]
https://cz-git.qbb.sh/zh/recipes/#%E8%BE%93%E5%85%A5%E6%A8%A1%E5%BC%8F
