### ISSUE TITLE
[Bug report] maxHeaderLength属性的计算方式应当优化

### ISSUE THREAD

**Issue by you-hengh** [Zhengqbbb/cz-git#167]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) CoreT i7-13800H
    Memory: 21.91 GB / 31.74 GB
  Binaries:
    Node: 20.11.1 - ~\AppData\Local\pnpm\node.EXE
    npm: 10.2.4 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
  npmPackages:
    commitizen: ^4.3.0 => 4.3.0
    cz-git: ^1.9.0 => 1.9.0
```

#### Concise Description
当我设置`maxHeaderLength`属性为20的时候, 在终端里什么都没写的情况下 提示只有4个字符可用
#### Expected behavior
设置`maxHeaderLength`属性为20的时候,在终端应该提示剩余20字符可用, 顺便说一句,括号里的字符能否支持配置为中文?
#### Screenshots or Screen Recording(if possible)
![2024-04-04_10-16-35](https://github.com/Zhengqbbb/cz-git/assets/34816426/900b470c-862d-4509-9ca2-abf9cedd0cd0)

我发现还有类似的变量 例如: maxSubjectLength breaklineNumber 等等

**Comment by Zhengqbbb** [comment]
header = type (类型) + scope (范围) + subject (简短描述)
