### ISSUE TITLE
[Bug report] 网站文档描述是否不当?

### ISSUE THREAD

**Issue by you-hengh** [Zhengqbbb/cz-git#168]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) CoreT i7-13800H
    Memory: 21.91 GB / 31.74 GB
  Binaries:
    Node: 20.11.1 - ~\AppData\Local\pnpm\node.EXE
    npm: 10.2.4 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
  npmPackages:
    commitizen: ^4.3.0 => 4.3.0
```

#### Concise Description
https://cz-git.qbb.sh/zh/config/engineer#maxheaderlength
在这里, 网站描述为`定义commit message中的 header 长度`, 但据我查看message节点,根本没有所谓`header`, 只有`subject`和`body`
#### Expected behavior
应当修正`maxheaderlength`为`maxSubjectLength`, 描述为`定义commit message中的 subject 长度`

应当修正原`maxSubjectLength`为`maxBodyLength`,描述为`定义commit message中的 body 长度`

#### Screenshots or Screen Recording(if possible)
![image](https://github.com/Zhengqbbb/cz-git/assets/34816426/57a0664b-5eca-4155-8ccc-ddb117a6141f)

顺便说一下 在提交过程中, 填写`"body": "填写更加详细的变更描述(可选)。使用 \"|\" 换行:",`的内容时,没有出现限制字符的提示,是否需要完善一下?

**Comment by Zhengqbbb** [comment]
header = type (类型) + scope (范围) + subject (简短描述)
