### ISSUE TITLE
[Bug report] Incorrect y/N prompt

### ISSUE THREAD

**Issue by sagargurtu** [Zhengqbbb/cz-git#174]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 340.53 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
  npmPackages:
    commitizen: ^4.3.0 => 4.3.0 
    cz-git: ^1.9.2 => 1.9.2
```

### Concise Description

The `confirmCommit` prompt shows `"Yneh"`.

<img width="457" alt="yneh" src="https://github.com/Zhengqbbb/cz-git/assets/18263719/c681b798-1a96-4f31-b7e1-4d0e3bd78501">

### Expected behavior

It should show `y/N` instead.

**Comment by Zhengqbbb** [comment]
> It should show `y/N` instead.

I don't think there is an error. Once the result meets expectations, I hope it can be submitted directly by <kbd>Enter</kbd>.
By the way, if you use <kbd>h</kbd>, you will understand why it's 'Yneh'.

**Comment by sagargurtu** [comment]
Oh gosh, my terminal isn't showing the options (y,n,e,h) below the `confirmCommit` prompt and I was wondered what that was. Resolving.

**Comment by sagargurtu** [comment]
Here's the screenshot.

<img width="484" alt="screenshot" src="https://github.com/Zhengqbbb/cz-git/assets/18263719/cef4d955-3370-4d27-9eca-62c193b9e3c0">

**Comment by Zhengqbbb** [comment]
Hey man, just <kbd>h</kbd> <sup>help</sup>

https://github.com/Zhengqbbb/cz-git/assets/40693636/23e56e11-3582-4389-b892-577d455801d6

**Comment by marios1861** [comment]
When selecting e, how can we customize the editor that will be used? I don't want to use vi. thanks

**Comment by marios1861** [comment]
I found out how to do it. In [cz-git/packages/src/shared/utils/editor.ts](https://github.com/Zhengqbbb/cz-git/blob/main/packages/cz-git/src/shared/utils/editor.ts) in the function editor, there is this line of choices:

```javascript
const editor = opts.editor || process.env.VISUAL || process.env.EDITOR || ed
```

where ed is vim on unix-like systems. If we change the script declaration in package.json: 

```json
"scripts": {
    "commit": "EDITOR='code --wait' cz"
}
```

The `process.env.EDITOR` option will be picked up. This is definitely missing from the docs and it would be very helpful so that others don't embark on a similar wild goose chase. Thanks for the package.

**Comment by Zhengqbbb** [comment]
> The `process.env.EDITOR` option will be picked up. This is definitely missing from the docs and it would be very helpful so that others don't embark on a similar wild goose chase. Thanks for the package.

I will add it in the FAQ docs, thank you for your support and pointing out this problem.

**Comment by Zhengqbbb** [comment]
> @marios1861  The `process.env.EDITOR` option will be picked up. This is definitely missing from the docs and it would be very helpful so that others don't embark on a similar wild goose chase. Thanks for the package.

Hi, The latest version 🌟(**v1.10.0**)🌟 add env `CZ_EDITOR` to control what EDITOR use. Avoid affecting others or env.

please have a try 💪 and check document information: https://cz-git.qbb.sh/faq/#modifying-the-editor-editor-used-when-choosing-to-edit-during-commit-confirmation-yneh

**Comment by marios1861** [comment]
Hi! Lovely work!! I would only add a link to the `cross-env` docs to keep it self contained. Thanks for the package 👑.
