### ISSUE TITLE
[Bug report] fail to run in msys2 & cygwin shell on windows: `spawn git ENOENT`

### ISSUE THREAD

**Issue by abcfy2** [Zhengqbbb/cz-git#181]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 3.52 GB / 15.92 GB
  Binaries:
    Node: 20.16.0 - ~\.nvm\versions\node\v20.16.0\bin\node.EXE
    npm: 10.8.1 - ~\.nvm\versions\node\v20.16.0\bin\npm.CMD
    pnpm: 9.7.0 - ~\AppData\Local\pnpm\pnpm.EXE
```

#### Concise Description

I can't run `czg` in `msys2` environment: https://www.msys2.org/

#### Steps to reproduce

```sh
pacman -S --noconfirm git
npm i -g czg
czg -a
```

#### Screenshots or Screen Recording(if possible)

```sh
$ czg -a
czg@1.9.4

? Select the type of change that you're committing: feat:     A new feature
? Denote the SCOPE of this change (optional): empty
? Write a SHORT, IMPERATIVE tense description of the change:
 [Infinity more chars allowed]
 add new file
? Provide a LONGER description of the change (optional). Use "|" to break new line:

? List any BREAKING CHANGES (optional). Use "|" to break new line:

? Select the ISSUES type of change (optional): skip

###--------------------------------------------------------###
feat: :sparkles: add new file
###--------------------------------------------------------###

? Are you sure you want to proceed with the commit above? Yes
spawn git ENOENT


```

**Comment by abcfy2** [comment]
I think this might be the unix path used by `git`: https://www.msys2.org/docs/git/

**Comment by Zhengqbbb** [comment]
Emmm. git command not found ?
Do you have the bin path of git in your Windows system environment variables? You should properly configure your local git environment before using this tool.

**Comment by abcfy2** [comment]
Hi @Zhengqbbb . Here's the result:

```sh
$ which git
/usr/bin/git

$ git --version
git version 2.46.0

$ node -e "require('child_process').spawn('git', ['-v'], { stdio: 'inherit' });"
git version 2.46.0
```

I guess the reason is not related by git path, but msys2 git uses cygwin which only support unix paths.

**Comment by abcfy2** [comment]
I think I should give up to use msys2 git: https://www.msys2.org/docs/git/

According to the official doc, this git will break down some git tools due to the confused by Unix paths.

And your project works properly with git-for-windows.

Thank you all the same.
