### ISSUE TITLE
Trim Extra Space Between Issue Prefix and Number in issuePrefixes Configuration

### ISSUE THREAD

**Issue by SebastianWesolowski** [Zhengqbbb/cz-git#184]
### 💭 Describe the feature

Description:
The issuePrefixes configuration should have an option to trim any extra spaces between the issue prefix and the issue number.

**Example Case:**
In .commitlintrc.js, the following configuration:

```js
module.exports = {
  issuePrefixes: [
    { value: 'SC-', name: 'SC' },
    { value: 'closed', name: 'closed:   ISSUES has been processed' },
  ],
};
```
Results in an unnecessary space between the prefix and the issue number when using the closed: prefix, as shown in the **screenshot:**
![czg](https://github.com/user-attachments/assets/04da34fc-db5f-467f-afe5-d1522f964fb6)

**Expected Behavior:**
There should be an additional option to trim any extra spaces between the prefix and the issue number, ensuring cleaner commit messages.

### 💡 Proposed Solution

There should be an additional option to trim any extra spaces between the prefix and the issue number, ensuring cleaner commit messages.

**Comment by Zhengqbbb** [comment]
Sorry about the commit message does not comply with the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification, so it will not be included as a feature.

![CleanShot 2024-09-13 at 13 42 27@2x](https://github.com/user-attachments/assets/dcdb903d-d77c-4f1a-aaea-a651042aa7ab)

---

**However, it can be completed with full custom configuration:**
https://cz-git.qbb.sh/config/engineer#formatmessagecb

```js
module.exports = {
    issuePrefixes: [
        { value: 'SC-', name: 'SC' },
        { value: 'closed', name: 'closed:   ISSUES has been processed' },
    ],
    formatMessageCB: ({ defaultMessage, footer }) => {
        if (!footer) {
            return defaultMessage
        }
        else {
            const lines = defaultMessage.split('\n')
            lines.pop()
            return lines.join('\n') + '\n' +footer.replace(/\s/g, '')
        }
    },
}
```

![CleanShot 2024-09-13 at 13 44 55@2x](https://github.com/user-attachments/assets/859d7a55-79ba-4140-9fb0-7f26db4eb25e)

**Comment by SebastianWesolowski** [comment]
Thanks for the custom configuration :)
