### ISSUE TITLE
[Bug report] When czg reads commitlint.config, the extends content cannot take effect

### ISSUE THREAD

**Issue by shlroland** [Zhengqbbb/cz-git#186]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 188.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/Library/Caches/fnm_multishells/47421_1726756844280/bin/node
    Yarn: 1.22.22 - ~/Library/pnpm/yarn
    npm: 10.8.2 - ~/Library/Caches/fnm_multishells/47421_1726756844280/bin/npm
    pnpm: 9.10.0 - ~/Library/Caches/fnm_multishells/47421_1726756844280/bin/pnpm
    bun: 1.1.20 - ~/.bun/bin/bun
    Watchman: 0.0.0 - /opt/local/bin/watchman
  npmPackages:
    cz-git: ^1.7.0 => 1.9.4
    czg: ^1.9.4 => 1.9.4
```

#### Concise Description
I configured a commitlint configuration file in the monorepo project. When I installed it in the root directory and used it in commitlint.config.js, the content of extends did not take effect.
like this

```js
// commitlint.config.js
export default {
  extends: ['@shlroland/commitlint-config']
}
```

#### Expected behavior
When I switch back to commitizen + cz-git, at this time, extends can take effect.

**Comment by Zhengqbbb** [comment]
Can you tell me what configuration is not effective? It works normally on my side.

.commitlintrc.cjs
```js
/** @type {import('czg').UserConfig} */
module.exports = {
    extends: ['@shlroland/commitlint-config'],
}
```

![CleanShot 2024-09-26 at 23 09 15@2x](https://github.com/user-attachments/assets/f4fbb747-bd77-4735-8a26-63b6a32043c2)

---

Try it to see if the configuration is overwritten.
```sh
CZ_DEBUG=1 czg -a
```

**Comment by shlroland** [comment]
> ```shell
> CZ_DEBUG=1 czg -a
> ```

<img width="763" alt="image" src="https://github.com/user-attachments/assets/e45b74cf-1b61-401e-8ff9-7fd426922e64">

The debug information is also normal.

Reproduced repository link: https://github.com/shlroland/lint-config/tree/tmp

**Comment by Zhengqbbb** [comment]
Strange 🤔. When I use the pre-release version, it returns to normal. I will debug it tomorrow. 
In the meantime, you can install `1.10.0-beta.1` for use, which will be released over the weekend.

```sh
pnpm i -D czg@next
npm i -g czg@next
```

**Comment by Zhengqbbb** [comment]
已确定属于上流包 `@commitlint/resolve-extends@19.0.3` bug

---

1. 我将所有 `@commitlint` 包升级到最新版本，发布 `1.10.0-beta.2` extends 表现正常
2. 我将 `@commitlint/resolve-extends` 降级为 `19.0.3`，发布 `1.10.0-beta.3` 表现异常

<img width="931" alt="image" src="https://github.com/user-attachments/assets/4a47a5dc-d495-4df2-bc58-24a3f993bc5e">

---

我将在周末发布修复版本 `v1.10.0`，将所有的 @commitlint 包升级为最新的 `v19.5.0`

**Comment by shlroland** [comment]
Thank you for your timely reply and your hard work in fixing the problem overnight. I'll try it out.

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.10.0)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. 🎉
