### ISSUE TITLE
[Feature Request] 我提供了一份中文版emoji 模板愿意贡献

### ISSUE THREAD

**Issue by you-hengh** [Zhengqbbb/cz-git#188]
### 💭 Describe the feature

开发者你好! 我提供了一份中文的emji模板, 你可以看看效果, 你可以看看视频效果

如果你有兴趣, 我可以直接提供文件, 也可以提交PR

### 💡 Proposed Solution

https://github.com/user-attachments/assets/f3c2d9d6-0976-4d51-8403-c4deea375d83

**Comment by Zhengqbbb** [comment]
是中文的 emoji 模版吗？或可以告知一下有什么不同吗
感觉可以通过下面两个配置实现
- https://cz-git.qbb.sh/zh/config/show#types
- https://cz-git.qbb.sh/zh/config/show#emojialign

**Comment by Zhengqbbb** [comment]
Btw emoji 前置效果是好看的，当初是因为前置的 emoji 不符合[Conventional Commits](https://www.conventionalcommits.org/zh/v1.0.0/) 
所以默认配置或模版都是放在中间。不然需要魔改 commitlint 否则默认的 commitlint 会不予通过

**Comment by you-hengh** [comment]
> Btw emoji 前置效果是好看的，当初是因为前置的 emoji 不符合[Conventional Commits](https://www.conventionalcommits.org/zh-hans/v1.0.0/) 所以默认配置或模版都是放在中间。不然需要魔改 commitlint 否则默认的 commitlint 会不予通过

是的 所以我没有安装 commitlint  , 算是图一乐吧 

这是提交效果:

![image](https://github.com/user-attachments/assets/f77913ee-5624-45a7-86cd-42f246f02340)

**Comment by shlroland** [comment]
> ### 💭 Describe the feature
> 开发者你好! 我提供了一份中文的emji模板, 你可以看看效果, 你可以看看视频效果
> 
> 如果你有兴趣, 我可以直接提供文件, 也可以提交PR
> 
> ### 💡 Proposed Solution
>  emoji._x264.mp4

终端好看，能告知怎么配置的吗

**Comment by you-hengh** [comment]
> > ### 💭 Describe the feature
> > 开发者你好! 我提供了一份中文的emji模板, 你可以看看效果, 你可以看看视频效果
> > 如果你有兴趣, 我可以直接提供文件, 也可以提交PR
> > ### 💡 Proposed Solution
> > emoji._x264.mp4
> 
> 终端好看，能告知怎么配置的吗

终端字体: FiraCode Nerd Font Mono 
终端主题: oh-my-posh 使用 craver.omp.json 

主题文件我自己稍微改了一下 因为默认的背景色不是透明的

**Comment by Zhengqbbb** [comment]
哈哈哈哈  是这一款吗？
![CleanShot 2024-09-29 at 14 14 36@2x](https://github.com/user-attachments/assets/3ab73297-559b-41fb-8c2f-4b9fcc19c903)

**Comment by shlroland** [comment]
> > Btw emoji 前置效果是好看的，当初是因为前置的 emoji 不符合[Conventional Commits](https://www.conventionalcommits.org/zh-hans/v1.0.0/) 所以默认配置或模版都是放在中间。不然需要魔改 commitlint 否则默认的 commitlint 会不予通过
> 
> 是的 所以我没有安装 commitlint , 算是图一乐吧
> 
> 这是提交效果:
> 
> ![image](https://private-user-images.githubusercontent.com/34816426/371772658-f77913ee-5624-45a7-86cd-42f246f02340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTg0OTcsIm5iZiI6MTcyODY1ODE5NywicGF0aCI6Ii8zNDgxNjQyNi8zNzE3NzI2NTgtZjc3OTEzZWUtNTYyNC00NWE3LTg2Y2QtNDJmMjQ2ZjAyMzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE0NDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YzQ2MWIwNGYyZjllNzAyZjYxMTVlNjE4YjhiNDVlODRkZGU3YWVhZWFkYTA2YWJmZmMzMDU3OTVkMzcyM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TizWH8WeP2YHem_I8ilxogrPDYTIwHAePpQGTZVDsbY)

今天突然看到这个 https://www.yuque.com/arvinxx-fe/workflow/commitlint-config-gitmoji-guide  emoji前置符合 gitmoji 规范，配合上这个规则是可以过 commitlint 的

**Comment by shlroland** [comment]
@you-hengh 能否提完整的模板参考一下呢？
