### ISSUE TITLE
[Feature Request] When the commit fails, it can remember the message of this failure and directly reuse it during the next commit.

### ISSUE THREAD

**Issue by shlroland** [Zhengqbbb/cz-git#191]
### 💭 Describe the feature

Often writing long messages because lint-staged does not pass or for other reasons, resulting in the need to write again or copy it the next time during the commit. If the previous message could be remembered, it would be very convenient. I also had such confusion when using cz before.

**Comment by Zhengqbbb** [comment]
> Often writing long messages because lint-staged does not pass or for other reasons

You can setting options ?  https://cz-git.qbb.sh/config/engineer#maxheaderlength or https://cz-git.qbb.sh/config/engineer#maxsubjectlength

> resulting in the need to write again or copy it the next time during the commit.

I have considered this issue before
1. Therefore, there is a **preview mode** for easy copying
2. In addition, there is an edit <kbd>e</kbd> provided in the final submission for last editing
3. Both cz and czg commands offer the `-r` option, which records the last commit to skip the prompt and use it directly

![CleanShot 2024-10-12 at 15 29 13@2x](https://github.com/user-attachments/assets/7d23d965-fc5b-42bb-9236-65974f153da6)


If you want every prompt to be recorded, the amount of information recorded is too large and the possibilities of each interaction are different. Therefore, unless a better CLI interaction mode emerges, I apologize that there will be no development.

**Comment by shlroland** [comment]
> > Often writing long messages because lint-staged does not pass or for other reasons
> 
> You can setting options ? [cz-git.qbb.sh/config/engineer#maxheaderlength](https://cz-git.qbb.sh/config/engineer#maxheaderlength) or [cz-git.qbb.sh/config/engineer#maxsubjectlength](https://cz-git.qbb.sh/config/engineer#maxsubjectlength)
> 
> > resulting in the need to write again or copy it the next time during the commit.
> 
> I have considered this issue before
> 
> 1. Therefore, there is a **preview mode** for easy copying
> 2. In addition, there is an edit e provided in the final submission for last editing
> 3. Both cz and czg commands offer the `-r` option, which records the last commit to skip the prompt and use it directly
> 
> ![CleanShot 2024-10-12 at 15 29 13@2x](https://private-user-images.githubusercontent.com/40693636/375937051-7d23d965-fc5b-42bb-9236-65974f153da6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTg2MjIsIm5iZiI6MTcyODcxODMyMiwicGF0aCI6Ii80MDY5MzYzNi8zNzU5MzcwNTEtN2QyM2Q5NjUtZmM1Yi00MmJiLTkyMzYtNjU5NzRmMTUzZGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3MzIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOWE4NzUzZTg1NjA1MTllY2VlZThkZjc2MWNkMDZkNGI5ZmZkMjlmNDNiMzMwZDExMTUyZGNmMTU5MmJjNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HaTu7x_qfGTndmoT2XPufskKwCCzi7SJP33VzFFlrpo)
> 
> If you want every prompt to be recorded, the amount of information recorded is too large and the possibilities of each interaction are different. Therefore, unless a better CLI interaction mode emerges, I apologize that there will be no development.

I’m sorry for not looking at the document carefully; -r is exactly what I want.

**Comment by Zhengqbbb** [comment]
Ok,`-r` is a very useful option in my opinion, LOL 🤗
![CleanShot 2024-10-12 at 15 37 30@2x](https://github.com/user-attachments/assets/173252cb-6580-41af-b59a-856c3508a93b)
