### ISSUE TITLE
[Feature Request] Provide a type helper function for config auto-complete

### ISSUE THREAD

**Issue by Mister-Hope** [Zhengqbbb/cz-git#193]
### 💭 Describe the feature

It's a bit annoying to use `as` in typescript and `@type` annotation in javascript.

Instead, a function helepr could be exported:

```ts
export const config = (userConfig: UserConfig) => UserConfig
```

This is exactly what a lot of tools like vite and vuepress are using.

Before:

```js
/** @type {import('cz-git').UserConfig} */
module.exports = {
  // ...
}
```

```ts
improt type { UserConfig } from 'cz-git'

export default {
  // ...
} as UserConfig
```

After:

```js
const { config } = require('cz-git');

module.exports = config({
  // ...
})
```

```ts
import { config } from 'cz-git';

export default config({
  // ...
})
```

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.11.0)🌟 released and provide config file type helper fn `defineConfig` and `definePrompt`
Docs Link: https://cz-git.qbb.sh/config/
💪 Please have a try. 👀 Let me know if there are still any issues. 🎉
