### ISSUE TITLE
[Feature Request]Is it possible to search not only for type

### ISSUE THREAD

**Issue by shlroland** [Zhengqbbb/cz-git#195]
### 💭 Describe the feature

czg seems to only search for type now, and does not search for name. 

I’m working on a set of templates that utilize [gitmoji](https://gitmoji.dev/), planning to use emojis to represent different types. However, if I list all the types associated with gitmoji, it becomes necessary to rely on searches for selecting which type to use.

If using emoji as a type, it is very unfriendly for semantic search.

### 💡 Proposed Solution

Therefore, I currently treat value merely as a search keyword and use `formatMessageCB` to format the message. However, there is one issue regarding the `allowBreakingChanges` field; it seems to require an exact match with type.value. If I insert multiple keywords into `type.value`, I need to fill in the exact same content in `allowBreakingChanges`, which is clearly not very elegant.

**Comment by shlroland** [comment]
related #191 188

**Comment by Zhengqbbb** [comment]
Try https://cz-git.qbb.sh/zh/config/show#typessearchvalue
