### ISSUE TITLE
[BUG report]: Cannot convert undefined or null to object. Node `v12.20.0` ~ `v14`

### ISSUE THREAD

**Issue by Zhengqbbb** [Zhengqbbb/cz-git#199]
### Discussed in https://github.com/Zhengqbbb/cz-git/discussions/198

<div type='discussions-op-text'>

Node: v12.20.0

<sup>Originally posted by **dayney** November  5, 2024</sup>
These errors were displayed when I reinstalled：
```
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

> yikuaiqian@2.1.1 prepare /Users/krui/git/work/purchase-weapp
> husky install

husky - Git hooks installed
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for cosmiconfig-typescript-loader@4.4.0: wanted: {"node":">=v14.21.3"} (current: {"node":"14.17.3","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: cosmiconfig-typescript-loader@4.4.0
```

after, I run the following command to give the prompt is
```
git add package*
git cz 
```

```
Cannot convert undefined or null to object
```
</div>

> Cannot convert undefined or null to object

- I have reproduced the issue, which is consistent with my suspicion. In `v1.9.4` - https://github.com/Zhengqbbb/cz-git/blob/main/CHANGELOG.md#194-2024-07-19
- Although the error for node v22 has been fixed, it introduced an incompatible error. I apologize for the inconvenience; please downgrade to `v1.9.3` first.

```sh
npm i -D cz-git@1.9.3
```

**Comment by Zhengqbbb** [comment]
@dayney First of all, thank you very much for pointing out this BUG.
1. After investigation, this bug appeared when switching from node-fetch to node-fetch-cjs #179, primarily to address issues with node v22 error.
2. Testing has shown that node-fetch-cjs has different issues in node v12, node v14, and node v16.

---

In response to this issue, the following changes were made in #200:
1. Changed node-fetch-cjs to dynamic import to ensure that `cz-git` and `czg` can run in node >= v12.20.
2. Added minimum version requirements for node (>= v16.5) in cases where node-fetch is needed in AI mode.


---

I plan to release v1.11.0 this weekend.
I have released a next pre-release version 🌟(v1.11.0-beta.2)🌟 for testing.
Welcome to try it out! 👀 Let me know if there are still any issues. 🎉

```sh
npm i -D cz-git@next
```

**Comment by dayney** [comment]
好的，感谢


Q.Ben Zheng ***@***.***>于2024年11月5日 周二20:20写道：

**Comment by Zhengqbbb** [comment]
@dayney 
The latest version 🌟(v1.11.0)🌟 released and should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. 🎉

**Comment by dayney** [comment]
think you, Now it works.

Q.Ben Zheng ***@***.***> 于2024年11月8日周五 23:00写道：
