### ISSUE TITLE
[Feature Request]scopes为空数组时，scope期望默认选中empty

### ISSUE THREAD

**Issue by qiqihaobenben** [Zhengqbbb/cz-git#34]
### 💭 Describe the feature

现有配置如下：
```
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
```
没有默认的scope但是还想要能自定义scope，现在默认选中的是custom，实际场景是大多数情况下scope为空，想要默认选中empty。

**Comment by Zhengqbbb** [comment]
> When the scope is empty, the default empty pin the top

Mainly because [customScopesAlign default is bottom](https://cz-git.qbenben.com/guide/options-show.html#customscopesalign). Logical judgment can be added on this basis.

**Comment by qiqihaobenben** [comment]
Yeah. I solved it by setting customScopesAlign to top at now.

`handleCustomTemplate` function In `until.ts`：
```
 if (!Array.isArray(target) || target.length === 0) {
    return result;
  }
```
I think this will solve the problem.

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.3.5)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. Thanks for you work! 🎉
