### ISSUE TITLE
[Feature Request] Optional prompt to use exclamation (!) to denote breaking change

### ISSUE THREAD

**Issue by sitiom** [Zhengqbbb/cz-git#38]
### 💭 Describe the feature

See Conventional Commits [examples](https://www.conventionalcommits.org/en/v1.0.0/#examples):
![image](https://user-images.githubusercontent.com/56180050/174933738-ff303050-430e-4a6e-83b6-071750babbc3.png)

### 💡 Proposed Solution

An option to denote an exclamation mark

**Comment by Zhengqbbb** [comment]
I have been following this option, you can check out this tweet.
Let me know if it solves your problem

https://twitter.com/antfu7/status/1536301374748913666

**Comment by sitiom** [comment]
> Received, thanks for the let me know more, you can look at this option [cz-git.qbenben.com/config/show.html#typesappend](https://cz-git.qbenben.com/config/show.html#typesappend) See if it can solve your needs first

This just adds additional types in addition to the default ones. I want to be able to append an exclamation mark to every type (`feat!:`, `chore!:`, `ci!:`, ...).



> I have been following this option, you can check out this tweet. Let me know if it solves your problem
> 
> [twitter.com/antfu7/status/1536301374748913666](https://twitter.com/antfu7/status/1536301374748913666)

This one is for changelogs, not for Commitizen.

**Comment by Zhengqbbb** [comment]
In the next version I will add an environment variable for better use.
e.g:`break=1 cz`In this way, an exclamation mark will be added after all types.

What better opinion do you have?

**Comment by sitiom** [comment]
I was thinking of an optional prompt "`Would you like to prefix an exclamation (!) mark to denote a breaking change? (Yn)`" right before the "`List any BREAKING CHANGES`" prompt.

**Comment by Zhengqbbb** [comment]
I also need to consider that users who use commitlint will return false so mark is not provided by default.

 I think there should be a configuration item to give prompt to cooperate with BREAKCHANGE

Environment variables are also prepared for no-config for anyway,
I will release cz-git cli in the next version
`break=1 cz` or
`czg break`

**Comment by sitiom** [comment]
> I also need to consider that users who use commitlint will return false so mark is not provided by default.

I'm using commitlint and using the exclamation mark works just fine.

**Comment by Zhengqbbb** [comment]
> > I also need to consider that users who use commitlint will return false so mark is not provided by default.
> 
> I'm using commitlint and using the exclamation mark works just fine.

great~ Maybe this feature needs more than cli.it will come soon

**Comment by Zhengqbbb** [comment]
@sitiom 
I think I'm almost done.
you see if there is any problem

Use the environment variable Demo :
![a](https://user-images.githubusercontent.com/40693636/174949733-d5cd7f0d-ac81-40e8-8cb9-158737330d7a.gif)

Can add options `markBreakingChangeMode: true` turn on the question of extra prompt:
demo:

![a](https://user-images.githubusercontent.com/40693636/174950214-b294413c-b2b4-4e5b-9b8d-38deab9e8485.gif)

**Comment by sitiom** [comment]
Looks good to me!

**Comment by Zhengqbbb** [comment]
> Looks good to me!

I expect that I will a release on the weekend, of course I want the cli to go live together, I will give a notice at that time, thank you for your suggestion

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.3.6)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. Thanks for you work! 🎉

Guide see: https://cz-git.qbenben.com/recipes/breakingchange.html

**Comment by sitiom** [comment]
Thanks, it works as intended so far.

**Comment by sitiom** [comment]
@Zhengqbbb Wait, if I input "no" in the breaking change prompt it won't ask for a breaking change footer. Regardless, it should still ask for a breaking change description because it is possible to omit the `!` if a breaking change footer exists (and vice versa).

**Comment by Zhengqbbb** [comment]
I didn't want to add another question, but that said, it should be added and matched with the `allowBreakingChanges` options.

**Comment by Zhengqbbb** [comment]
This is how I see it, if this mode is turned on, if you choose no, then it means that there is no BREAKINGCHANGE

**Comment by sitiom** [comment]
Not necessarily, you can omit the `!` when there is a `BREAKING CHANGE:` footer and vice versa. See the [examples](https://www.conventionalcommits.org/en/v1.0.0/#examples) on the CC site:

>## Commit message with description and breaking change footer
>```
>feat: allow provided config object to extend other configs
>
>BREAKING CHANGE: `extends` key in config file is now used for extending other config files
>```
>
>## Commit message with `!` to draw attention to breaking change
>```
>feat!: send an email to the customer when a product is shipped
>```
>
>## Commit message with both `!` and BREAKING CHANGE footer
>```
>chore!: drop support for Node 6
>
>BREAKING CHANGE: use JavaScript features not available in Node 6.
>```

**Comment by sitiom** [comment]
Just thought of it now, since both options are not related to each other, shouldn't the `!` prompt be already there by default and no config/environment var is needed?

**Comment by Zhengqbbb** [comment]
wait five mins

**Comment by Zhengqbbb** [comment]
> I just thought of it now; since both options can be omitted from each other, shouldn't the `!` prompt be already there by default, and no config/environment var is needed?

NO, this will lose the no-config convenience, and you ignore a point that only feat fix will have this question by default

**Comment by sitiom** [comment]
Oh, Yeah, except those not defined in `allowBreakingChanges` of course.

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.3.7)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. Thanks for you work! 🎉
Thanks again for your advice!!!

**Comment by Zhengqbbb** [comment]
BTW you can try `npx czg` in your project 😁😁😁
it will be awsome

**Comment by sitiom** [comment]
> The latest version 🌟(v1.3.7)🌟 should be resolve this issue request , please have a try. 💪 👀 Let me know if there are still any issues. Thanks for you work! 🎉 Thanks again for your advice!!!

It works as intended now, thanks!

> BTW you can try `npx czg` in your project 😁😁😁 It will be awsome

Thanks. I'm used to having a `git cz` alias, though. Can you add it for that one?

**Comment by Zhengqbbb** [comment]
> Can you add it for that one?

I will say no. I'm also a shell developer, I know this behavior is very disruptive to the user's environment. it's up to the user to decide and create.
😇 Thx u support

**Comment by sitiom** [comment]
@Zhengqbbb the issue seems to still haven't been fixed in `czg`:
![image](https://user-images.githubusercontent.com/56180050/175776948-ade4f45b-bd8b-4089-8d44-b7bf9b11ebd9.png)

**Comment by Zhengqbbb** [comment]
Is there any operation steps, It fine on my env

**Comment by sitiom** [comment]
There's still a break mode in `czg`? It doesn't match the behavior in the adapter?

**Comment by Zhengqbbb** [comment]
> There's still a break mode in `czg`? It doesn't match the behavior in the adapter?

You mean, BREAKINGCHANGE is not appearing, Emmm `allowBreakingChanges` is a problem, I will fix it next week

**Comment by sitiom** [comment]
Oh ok, it seems that I have misunderstood it, sorry. Just ignore my previous comments, everything is working fine.

**Comment by Zhengqbbb** [comment]
> Oh ok, it seems that I have misunderstood it, sorry. Just ignore my previous comments, everything is working fine.

Use the CLI a lot and you'll build muscle memory and experience the feeling of being fast and simple! ❤️

**Comment by Zhengqbbb** [comment]
> Thanks. I'm used to having a `git cz` alias, though. Can you add it for that one?

Through the study of this [article](https://blog.sebastian-daschner.com/entries/custom-git-subcommands), I have changed my previous idea and added a command line entry `git-czg`, I will release a version **v1.3.10** on the weekend, then you can  use `git czg` to start CLI

> Git automatically resolved subcommands from executables in the PATH that follow the naming convention git-<subcmd>. These subcommands can be executed with git <subcmd>.

🤗

**Comment by sitiom** [comment]
Interesting, that's why git recognizes `git cz` 🤔
