### ISSUE TITLE
[Feature Request] czg not loads ~/.czrc or ~/.cz.json global config

### ISSUE THREAD

**Issue by tomasky** [Zhengqbbb/cz-git#42]
### 💭 Describe the feature

 ~/.czrc or ~/.cz.json   works

**Comment by Zhengqbbb** [comment]
Use the `commitizen` CLI or the `czg` CLI?
Also send your config file

**Comment by tomasky** [comment]
czg

**Comment by Zhengqbbb** [comment]
works, 
please check if it's the latest version number, and the project file, it may be interfering

![a](https://user-images.githubusercontent.com/40693636/176127224-522569b1-79da-4591-83d9-3b255d2f16a3.gif)

**Comment by tomasky** [comment]
```shell
cat ~/.czrc
{
   "scopes": ["app", "home", "account", "comment"] 
}


czg
czg@1.3.8

? Select the type of change that you're committing: feat:     A new feature
? Denote the SCOPE of this change (optional): 
❯ empty 
  custom 

```

**Comment by Zhengqbbb** [comment]
send `npx envinfo --system --binaries --npmPackages cz-git --npmPackages commitizen --npmPackages czg --npmGlobalPackages cz-git --npmGlobalPackages commitizen --npmGlobalPackages czg`

**Comment by Zhengqbbb** [comment]
Thx u support. Have enjoy~ It will be awesome ❤️

**Comment by tomasky** [comment]
but why /tmp dir not load ~/.czrc

**Comment by Zhengqbbb** [comment]
> but why /tmp dir not load ~/.czrc

I guess you be using WSL Windows,
You can go to the `~` directory and use the `pwd` command.
Check the results, since I don't have a Windows computer, I guess I can't find back or unable to find system level directory

**Comment by tomasky** [comment]
No ,i use ubuntu 16 lts , 32bit
