### ISSUE TITLE
[Feature Request] v1.3.9 plan: add `emojiAlign`  | add `alias`

### ISSUE THREAD

**Issue by Zhengqbbb** [Zhengqbbb/cz-git#43]
### 💭 Describe the feature

- [x] add `emojiAlign` support emoji is placed before type
- [x] add `alias` to directly output the defined commit message

### Add `emojiAlign`
> support emoji is placed before type
The format alignment is really nice, but considering the validation with following [Angular commit](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits), the default is `center`
- type: `"left"` | `"center"` | `"right"`
<img width="183" alt="image" src="https://user-images.githubusercontent.com/40693636/176343378-8b26942e-ddc6-402a-8d4e-eb45d59423f2.png">

---

### Add `alias`
We may encounter commit messages that are often output, such as `docs: fix typos`, if we define like.
```json
{
 "alias": {
     "df": "docs: fix typos"
  }
}
```
Usage:
1. `czg :df`
2. `czg --alias="df"`
3. `cz_alias="df" git cz`
4. `cz_alias="df" cz`

You can directly output `docs: fix typos` commit message
It will be awesome and convenient.

**Comment by Zhengqbbb** [comment]
But I'm not sure if this options name is good
@chrisbbreuer @jaklan If have time,  can help me check together. I will appreciate it.

**Comment by jaklan** [comment]
@Zhengqbbb "emojiAlign" sounds pretty fine for me. Can you show some examples of all 3 options: "left", "center", "right"?  I'm not sure how to interpret "center".

**Comment by Zhengqbbb** [comment]
> @Zhengqbbb "emojiAlign" sounds pretty fine for me. Can you show some examples of all 3 options: "left", "center", "right"? I'm not sure how to interpret "center".

Yep, the "center" expression not good.

default:center 
<img width="830" alt="wecom-temp-7cd4d7ef6183ab9ccb902abe83eeae20" src="https://user-images.githubusercontent.com/40693636/176441824-058c78ff-9f58-4fcf-a7ff-916f8b250deb.png">
left:
<img width="859" alt="wecom-temp-594d5698b5368dbb01ba561f31ad1161" src="https://user-images.githubusercontent.com/40693636/176441862-cc662aa2-b73f-47b1-81cc-e055cd17a1a3.png">
right:
<img width="812" alt="wecom-temp-23a04ada9e31c4b560f18be8ae4af2d6" src="https://user-images.githubusercontent.com/40693636/176441890-95c8eec9-5c1f-440d-bc4c-c49e28f2f157.png">

**Comment by Zhengqbbb** [comment]
> I see, that's what I assumed, just wanted to make sure 🙂 If you provide examples in docs, imho `center` is okay - any other word can be even more confusing.

Thx~ 😊

**Comment by chrisbbreuer** [comment]
Love the feature!

I would potentially think about the following naming adjustment:

`emojiAlign` -> `emojiAlignment`

We sparingly use the `noun + imperative` convention throughout the codebase. And it seems a little more clear because `Align` could indicate it accepts more than "just a string." 

While this is just a minor adjustment, thanks for all the work ❤️

**Comment by Zhengqbbb** [comment]
@chrisbbreuer 

Thx~ 😊

**Comment by Zhengqbbb** [comment]
⭐️ v1.3.9 ⭐️ has been released 🥳

- About `emojiAlign `: https://cz-git.qbenben.com/config/show.html#emojialign
- About `alias`: https://cz-git.qbenben.com/recipes/alias.html
- Share my alias config: 
https://github.com/Zhengqbbb/cz-git/blob/da02332ef04252b83eea3e64a86c8657578b79e1/.commitlintrc.js#L23-L28

Have a enjoy ~
