### ISSUE TITLE
[Bug report]: No found commit message cache in current repo

### ISSUE THREAD

**Issue by wjw-gavin** [Zhengqbbb/cz-git#48]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbenben.com/faq/)

### 📄 System Info

```shell
macos
node.js  18.4
czg: 1.3.9
```

#### Concise Description
When I execute the `czg --retry`,  I get an error `No found commit message cache in current repo`, what should I do?

**Comment by Zhengqbbb** [comment]
Use `cz` | `git cz` or `czg` command to make a commit, then the message cache of the current project directory will be recorded, then use `czg -r`

This option is good for when you are doing documentation changes, CI configuration changes

**Comment by Zhengqbbb** [comment]
Anyway need to do the first commit message.

**Comment by wjw-gavin** [comment]
> Anyway need to do the first commit message.

Yes, in fact I have made commits.... o(╥﹏╥)o

**Comment by Zhengqbbb** [comment]
> > Anyway need to do the first commit message.
> 
> Yes, in fact I have made commits.... o(╥﹏╥)o

LOL, I will modify the error message in the next version, thanks for the reminder.

I used it to modify CI a few days ago😵
![image](https://user-images.githubusercontent.com/40693636/179143743-2eea5800-4e61-4eda-96a3-c85c1188268f.png)

**Comment by Zhengqbbb** [comment]
optimize `czg  --retry` option cache error message:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/40693636/179153726-1ce0b06e-d35e-450e-b1db-a303a31c6505.png">
