### ISSUE TITLE
[Ask For Help] the emojis are not showing in the CLI.

### ISSUE THREAD

**Issue by tomavic** [Zhengqbbb/cz-git#49]
### 💭 Describe the feature

I have couple questions:

- What is diff betn. `cz` and `czg`
- When to use `.commitlintrc.js` and `cz.config.js` and Do I need to install extra packages in case of `.commitlintrc.js`?
- I've tried to use [emoji-template](https://cz-git.qbenben.com/config/#emoji-template) as described but with `cz.config.js` in the root folder but the emojis are not showing in the CLI.
 I am using normal configs

```json
  "config": {
    "commitizen": {
      "path": "node_modules/cz-git"
    }
  },

```

Thanks

### 💡 Proposed Solution

Appreciate all efforts in the documentation but this part needs to be clarified specially the part of `czg`

**Comment by Zhengqbbb** [comment]
@tomavic 
> * What is diff betn. `cz` and `czg`

https://cz-git.qbenben.com/cli/why.html#what-is-different-from-cz-git

>I am using normal configs
please copy configfile, config file name and tell me what u using command `cz` or `czg`

**Comment by Zhengqbbb** [comment]
https://user-images.githubusercontent.com/40693636/179258161-e0658ec2-0480-44c3-b8d5-52a4e76be205.mp4

I turn on discussions , if u need help can tell me. I will quick response, after all, I want the badge lol~ 😂

**Comment by tomavic** [comment]
> @tomavic
> 
> > * What is diff betn. `cz` and `czg`
> 
> https://cz-git.qbenben.com/cli/why.html#what-is-different-from-cz-git
> 
> * If u using `cz` will star commitizen CLI and cz-git adapter(can understand plugin ?)
> * If u using `czg` will star czg CLI
> 
> > I am using normal configs
> 
> please copy configfile, config file name and tell me what u using command `cz` or `czg`



> @tomavic
> 
> > * What is diff betn. `cz` and `czg`
> 
> https://cz-git.qbenben.com/cli/why.html#what-is-different-from-cz-git
> 
> * If u using `cz` will star commitizen CLI and cz-git adapter(can understand plugin ?)
> * If u using `czg` will star czg CLI
> 
> > I am using normal configs
> 
> please copy configfile, config file name and tell me what u using command `cz` or `czg`

First I don't know what is `czg` 😂 I just used `cz`. 
I installed `npm i -D cz-git@1.3.9 commitizen@4.2.4`

Then I added config file `cz.config.js` in the root directory


```js
// cz.config.js
/** @type {import('cz-git').CommitizenGitOptions} */
module.exports = {
  alias: { fd: "docs: fix typos" },
  messages: {
    type: "Hey! Select the type of change that you're committing:",
    scope: "Denote the SCOPE of this change (optional):",
    customScope: "Denote the SCOPE of this change:",
    subject: "Write a SHORT, IMPERATIVE tense description of the change:\n",
    body: 'Provide a LONGER description of the change (optional). Use "|" to break new line:\n',
    breaking: 'List any BREAKING CHANGES (optional). Use "|" to break new line:\n',
    footerPrefixsSelect: "Select the ISSUES type of changeList by this change (optional):",
    customFooterPrefixs: "Input ISSUES prefix:",
    footer: "List any ISSUES by this change. E.g.: #31, #34:\n",
    confirmCommit: "Are you sure you want to proceed with the commit above?"
  },
  types: [
    { value: "feat", name: "feat:     ✨  A new feature", emoji: ":sparkles:" },
    { value: "fix", name: "fix:      🐛  A bug fix", emoji: ":bug:" },
    { value: "docs", name: "docs:     📝  Documentation only changes", emoji: ":memo:" },
    { value: "style", name: "style:    💄  Changes that do not affect the meaning of the code", emoji: ":lipstick:" },
    { value: "refactor", name: "refactor: ♻️   A code change that neither fixes a bug nor adds a feature", emoji: ":recycle:" },
    { value: "perf", name: "perf:     ⚡️  A code change that improves performance", emoji: ":zap:" },
    { value: "test", name: "test:     ✅  Adding missing tests or correcting existing tests", emoji: ":white_check_mark:" },
    { value: "build", name: "build:    📦️   Changes that affect the build system or external dependencies", emoji: ":package:" },
    { value: "ci", name: "ci:       🎡  Changes to our CI configuration files and scripts", emoji: ":ferris_wheel:" },
    { value: "chore", name: "chore:    🔨  Other changes that don't modify src or test files", emoji: ":hammer:" },
    { value: "revert", name: "revert:   ⏪️  Reverts a previous commit", emoji: ":rewind:" }
  ],
  useEmoji: true,
  emojiAlign: "center",
  themeColorCode: "",
  scopes: [],
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: "bottom",
  customScopesAlias: "custom",
  emptyScopesAlias: "empty",
  upperCaseSubject: false,
  markBreakingChangeMode: false,
  allowBreakingChanges: ['feat', 'fix'],
  breaklineNumber: 100,
  breaklineChar: "|",
  skipQuestions: [],
  issuePrefixs: [{ value: "closed", name: "closed:   ISSUES has been processed" }],
  customIssuePrefixsAlign: "top",
  emptyIssuePrefixsAlias: "skip",
  customIssuePrefixsAlias: "custom",
  allowCustomIssuePrefixs: true,
  allowEmptyIssuePrefixs: true,
  confirmColorize: true,
  maxHeaderLength: Infinity,
  maxSubjectLength: Infinity,
  minSubjectLength: 0,
  scopeOverrides: undefined,
  defaultBody: "",
  defaultIssues: "",
  defaultScope: "",
  defaultSubject: ""
};

```

Then I added my npm script

```json
    "cm": "git czg"
```

and when I run `npm run cm` I got 

```shell
my-app ➤ npm run cm                                                                git:feat/add-commit-hooks*

> hitchit-admin@0.0.0 cm
> git cz

cz-cli@4.2.4, cz-git@1.3.9

? Hey! Select the type of change that you're committing: Use arrow keys or type to search
❯ feat:     ✨  A new feature 
  fix:      🐛  A bug fix 
  docs:     📝  Documentation only changes 
  style:    💄  Changes that do not affect the meaning of the code 
  refactor: ♻️   A code change that neither fixes a bug nor adds a feature 
  perf:     ⚡️  A code change that improves performance 
  test:     ✅  Adding missing tests or correcting existing tests 
```

Looks like It's working now LOL xD 

I have changed the config file from `.cz.config.js` to `cz.config.js`. I believe this is the reason that make it work. Maybe !!

**Comment by tomavic** [comment]
> discussions



> 2022-07-15.23-39-09.mp4 
> I turn on [discussions](https://github.com/Zhengqbbb/cz-git/discussions) , if u need help can tell me. I will quick response, after all, I want the badge lol~ 😂

regarding this format `fix(root): :bug: edit configs commitizen`
The emojis are being displayed as :sparkles: 

Could this be changed to display the actual emoji?

**Comment by Zhengqbbb** [comment]
> Could this be changed to display the actual emoji?

Of course, Github supports uploading emoji/unicode directly,
But I need to guarantee compatibility because not only GitHub
So the default is emoji code

**Comment by tomavic** [comment]
> > Could this be changed to display the actual emoji?
> 
> Of course, Github supports emoji/unicode directly, But I need to guarantee compatibility because not only GitHub So the default is emoji code

So the "Safest" way to do it is writing it like this way :hammer: :sparkles: and so on?

**Comment by Zhengqbbb** [comment]
> So the "Safest" way to do it is writing it like this way `:hammer:` `:sparkles:` and so on?

I admit that it is not intuitive, and in some terminal apps with poor interactivity, emoji/unicode no support  that there will be **squares** in the preview. 😨😱

**Comment by Zhengqbbb** [comment]
> Now I want to generate changelog, how can I do this using semantic release?

https://github.com/Zhengqbbb/cz-git/discussions

I admit i want this badge 😂

**Comment by Zhengqbbb** [comment]
> I just used `cz`. I installed `npm i -D cz-git@1.3.9 commitizen@4.2.4`
BTW 👀👀👀👀
<img width="691" alt="image" src="https://user-images.githubusercontent.com/40693636/179276365-1aa68184-e61b-40ff-9d4c-d2761036adb0.png">

**Comment by tomavic** [comment]
> > I just used `cz`. I installed `npm i -D cz-git@1.3.9 commitizen@4.2.4`
> 
> BTW 👀👀👀👀 <img alt="image" width="691" src="https://user-images.githubusercontent.com/40693636/179276365-1aa68184-e61b-40ff-9d4c-d2761036adb0.png">

Yeah till now I am still confused what is czg 😂

**Comment by Zhengqbbb** [comment]
> Yeah till now I am still confused what is czg 😂

Let try it:
```shell
npm install czg -D
```



```diff
-  "cm": "git czg"
+  "cm": "czg"
```


```shell
npm run cm
```

---

If your team use **global** command `cz` or `git cz` will use `cz-git` plugin
If your team use `npm run cm` will use `czg` cli

`czg` more suitable as a dev dependency than `commitizen` smaller, simpler and lighter
