### ISSUE TITLE
[Feature Request] a config for `body-leading-blank` in commitlint

### ISSUE THREAD

**Issue by tui95** [Zhengqbbb/cz-git#52]
### 💭 Describe the feature

Is it possible to add a config for [`body-leading-blank`](https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md#body-leading-blank) option in commitlint?

### 💡 Proposed Solution

By setting an option `bodyLeadingBlank` to `true` in a config file, a new line will be added between commit subject and body.

**Comment by Zhengqbbb** [comment]
Could u can provide a demo:
like
```
chore: update config

- eslint config
- vscode config
```

**Comment by tui95** [comment]
What I meant was I'd like a feature where when set, will add a new line between the commit subject and commit body automatically.

Sorry. I don't have any config

> Could u can provide a demo: like
> 
> ```
> chore: update config
> 
> - eslint config
> - vscode config
> ```

since I use this library via the command line.

**Comment by Zhengqbbb** [comment]
Sorry if you misunderstood me, it's actually an example msg lol 😂 
like 🤔
```
chore: update config


- eslint config
- vscode config
```

mean there r double new line?

**Comment by tui95** [comment]
Oh, I see. I'd like only a single new line like the one in the [conventional commits example](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-multi-paragraph-body-and-multiple-footers).

**Comment by Zhengqbbb** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/40693636/180010619-f4145d40-0586-4b6e-adb7-27b5309f2e71.png">

**Comment by Zhengqbbb** [comment]
Currently, there will be blank lines !!!
I thought this option was an extra line lol 😂

**Comment by tui95** [comment]
Sorry. It already works. I misunderstood the commit display in the github UI

**Comment by Zhengqbbb** [comment]
What makes you misunderstood, you can say it directly and I will see how to improve 😎

**Comment by tui95** [comment]
It's my understanding about github UI that's not related to this tool
