### ISSUE TITLE
[Feature Request] Would you like to try better-scripts？

### ISSUE THREAD

**Issue by iamyoki** [Zhengqbbb/cz-git#53]
### 💭 Describe the feature

Hi, I am the author of [better-scripts](https://github.com/iamyoki/better-scripts), it's a great cli tool to help you reorganize npm scripts, would you like to give it a  try? Please assign me if you would, I'll make a PR.

**Comment by Zhengqbbb** [comment]
> Hi, I am the author of [better-scripts](https://github.com/iamyoki/better-scripts), it's a great cli tool to help you reorganize npm scripts, would you like to give it a try? Please assign me if you would, I'll make a PR.

Hi, nice to receive your suggestion
Can you tell me what are the advantages of better-scripts? 
- UI ? 
- Command param handling ?
- Current repo project management ?

**Comment by iamyoki** [comment]
@Zhengqbbb Thank you for your response.

The advantages based on how you use it, there are some recommended progressive ways:

## Use better-scripts as a npm scripts docs or runner
No configuration needed.

```sh
npx better-scripts
```

It will show all your scripts as a keyword searchable and arrow key interactive prompts

Example in naive-ui
![image](https://user-images.githubusercontent.com/74389358/183698487-b22f1515-fa36-42b9-9b10-911f9cb19f35.png)

## Add emoji and description for npm scripts
Just a little configuration

```json
{
  "dev": ["pnpm run dev", "Start a development server"],
  ...
}
```

Example in naive-ui
![image](https://user-images.githubusercontent.com/74389358/183699315-39117c86-35da-46fb-9b86-e90616e4d5a6.png)

## Group a bunch of scripts
It's nasty writing like these
```
"build": ....,
"build:lib": ...,
"build:components":...,
"build:types": ...,
```

So we move these under a child scripts in config
![image](https://user-images.githubusercontent.com/74389358/183699824-b134c0f5-5927-4285-8af6-4ffaa1df3b21.png)

Now let's play it step by step and always keep the [Magic number 7](https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two)

![iShot2022-08-09 23 56 14](https://user-images.githubusercontent.com/74389358/183700421-8a56836e-c55c-48e7-b515-e46a7e2fe151.gif)

## More advanced usage can be discovered by you

https://github.com/iamyoki/better-scripts

**Comment by Zhengqbbb** [comment]
Great～ node project script management
Wecome ～
I actually have it though, because I'm a shell lib developer 😄

<img width="911" alt="image" src="https://user-images.githubusercontent.com/40693636/183706606-6ad71d97-0b87-4fac-9f51-e605b4f9eef3.png">

<img width="971" alt="image" src="https://user-images.githubusercontent.com/40693636/183706653-c7e0ac6c-4a4d-48fc-a6ff-5d1ea8fd8f66.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/40693636/183706743-1c27af25-d9f3-4221-9901-eae03c61ee32.png">

**Comment by iamyoki** [comment]
That's why I'm reaching you. You are more professional than me. I'll give a PR tomorrow for your project, you can try and see if you want to merge.

**Comment by Zhengqbbb** [comment]
> That's why I'm reaching you. You are more professional than me. I'll give a PR tomorrow for your project, you can try and see if you want to merge.

 Thx. Looking forward to your work. GN👀🌙
