### ISSUE TITLE
[Feature Request] Custom formatter

### ISSUE THREAD

**Issue by thlmenezes** [Zhengqbbb/cz-git#57]
### 💭 Describe the feature

I've been using [commitizen-emoji](https://github.com/zorgick/commitizen-emoji) for a while now, and found this library as a way to remove duplicated configs between commitzen and commitlint.

But, currently I see you only support the angular output; and with no clear way, in my testing, to replace or omit the type output.

the commit format I'm targeting is as follows:

`<gitmoji>(<scope>): <subject>`

scope being optional

Compared to Default Angular Commits
`<type>(<scope>): <subject>`

Currently with cz-git I've managed to create commits like
```
feat: ✨ <subject>
feat(<scope>): ✨ <subject>
```

But I'm aiming for something like
```
✨ <subject>
✨ (<scope>): <subject>
```

### 💡 Proposed Solution

Enable users to customize their formatter with:
- sending their own custom function: receiving arguments corresponding to answers from the form view, and returning a string (title);
- implement a boolean argument `conventionalFormat` with default `true`, to enable the user to opt out of angular commit style

Example:

[formatTitle.ts](https://github.com/zorgick/commitizen-emoji/blob/94908c9a32c51885f94c8745431d5b891a56f7a1/src/lib/formatters/formatTitle.ts#L10)
```ts
export const formatTitle: FormatTitleType = ({ type, scope, subject }, config) => {
  const formattedScope = formatScopeOption(scope)
  const prelude = config.conventionalFormat
    ? `${type.emoji} ${type.name}${formattedScope}:`
    : `${type.emoji}${formattedScope ? ' ' + formattedScope + ':' : ''}`

  return `${prelude} ${subject}`
}
```

Example usage
```ts
const arguments = {
  type: {
    emoji: '✨',
    name: 'feat',
  },
  scope: 'mobile',
  subject: 'login screen'
}

console.log(formatTitle(arguments, {conventionalFormat: true}))  // ✨ feat (mobile): login screen
console.log(formatTitle(arguments, {conventionalFormat: false})) // ✨ (mobile): login screen
```

I believe there's some work to do on field type....type (ts typing) and fine-tuning, but I'm open to help in the conversation

**Comment by Zhengqbbb** [comment]
Hi, Thank you for your attention ❤️️
my personal understanding is **feat => ✨** 🤔
---
Maybe custom options `types` can help u  if so~
https://cz-git.qbb.sh/config/show.html#types
Have try ~

```
types: [
      {value: '✨', name: '✨ feat:     A new feature'},
       ...
    ],
```

![image](https://user-images.githubusercontent.com/40693636/185030377-a2189d46-50e9-4842-b314-a0238c6f43fb.png)

**Comment by Zhengqbbb** [comment]
- [ ] The above solution may have problems in search
     because the current search is based on value, and a switch needs to be provided to search for name
     I will support it in this weekend release

But need to provide format message option I need to think about it over the weekend 🤔

Anyway u can try this way, See if it solves your problem， just tell me ~ 🤗

**Comment by thlmenezes** [comment]
I appreciate the answer, this solves the issue; with the tradeoff being losing the search capabilities (my current cz search selects ✨ when typing 'feat'). Found that solution, but seemed like a hack, so I figured I should open the issue.

I will wait for the search update to try again, with this solved I'll move my setup to using cz-git.

**Comment by Zhengqbbb** [comment]
> I will wait for the search update to try again, with this solved I'll move my setup to using cz-git.

I will do it in weekend~
```
types: [
      {value: '✨', name: '✨ feat:     A new feature'},
       ...
],
```

current:
- fuzzy search in `value`

next version:
- add switch option can support fuzzy search in `name`

~

**Comment by Zhengqbbb** [comment]
@thlmenezes 
⭐️ v1.3.11 ⭐️ has been released 🥳 

There are two way can realize u  issue request:
1. as emoji to `type` value
```js
types: [
      {value: '✨', name: '✨ feat:     A new feature'},
       ...
],
typesSearchValueKey: false
```

2. you can use `formatMessageCB ` callback fn to custom finally message
```
formatMessageCB: ({ emoji, scope, subject }) => {
          return scope
            ? `${emoji}(${scope}): ${subject}`
            : `${emoji} ${subject}`
        }
```

please have a try. 💪
👀 Let me know if there are still any issues. Thanks for you work! 🎉
Thanks again for your advice!!!

**Comment by thlmenezes** [comment]
Will test the new release this week for sure and provide feedback

**Comment by thlmenezes** [comment]
Thank youuuuuu, it works like a charm; you can close the issue now.
