### ISSUE TITLE
commitlint `body-max-line-length` config is not applied

### ISSUE THREAD

**Issue by hubertkuoch** [Zhengqbbb/cz-git#6]
Hi - Thanks for this useful library.

Just a quick one since the doc says "cz-git is linked with `commitlint`", thought we can use the rules directly in the `.commitlintrc.js` file and those would be reflected in git-cz as well but when adding:

```zsh
/** @type {import('cz-git').UserConfig} */
const commitlintConfig = {
  rule: {
    "body-max-line-length": () => [2, "always", 72],
  },
  
  // other config
  },
}

module.exports = commitlintConfig
```

the body still wraps at a count of 100 characters. How can solve this please? 

Thanks a lot

**Comment by Zhengqbbb** [comment]
Thank you for your comments. Currently, I have completed type and scope, are there any other commitlint requirements? I think I can achieve them soon

**Comment by hubertkuoch** [comment]
Not for now thanks to the default configuration which I think are well chosen. It was just a  "cherry-on-the-cake" kind of ask to configure the body line length wrap more easily since I think the latter is customised quite often to 72 char count.

**Comment by Zhengqbbb** [comment]
this feature is done. verison: 1.2.2
docs: https://cz-git.qbenben.com/guide/option-engineer.html#breaklinenumber

You can only set commitlintConfig `body-max-line-length`.
Sure. if you want to set global or not use commitlint. you can use option `breaklineNumber`.
Auto breaking line base word completeness. you can with manual line break `breaklineChar`.

Thank you suggestion~
