### ISSUE TITLE
[Bug report] cz git 请求失败是不是将代码回退 ？

### ISSUE THREAD

**Issue by jahnli** [Zhengqbbb/cz-git#61]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```shell
请求失败是不是将代码回退 ？
```

#### Concise Description
请求失败是不是将代码回退 ？

**Comment by jahnli** [comment]
我尝试cz git 几次失败后，我代码消失了

**Comment by Zhengqbbb** [comment]
cz git 只是封装消息提取和 git commit操作
不会对仓库代码有其他操作 或是 git 操作
如有疑问请提供最小复原例子或仓库 我可以协助看看

**Comment by jahnli** [comment]
是否可以留个联系方式

**Comment by jahnli** [comment]
感觉像把代码还原了， 包括之前创建的文件等，也不见了

**Comment by Zhengqbbb** [comment]
首先应该不是 cz git 请求失败，而是使用 cz-git commit 后发生的事情导致了 `git stash`
你可以使用 `git stash list` 进行确定
我猜大概率是因为 你有其他的 `git hook` 事件 使用了 `lint-staged` 导致
link： https://github.com/okonet/lint-staged/issues/929

所以我将关闭此  ISSUE.希望你可以在社区找到解决方案 或是 不使用 `lint-staged`

**Comment by Zhengqbbb** [comment]
`--no-stash                         disable the backup stash, and do not revert in case of errors`
https://github.com/okonet/lint-staged
试试: hook 命令 可以添加`--no-stash`

**Comment by jahnli** [comment]
OK， 我尝试下

**Comment by Zhengqbbb** [comment]
> OK， 我尝试下

https://github.com/vbenjs/vue-vben-admin/issues/2064#issuecomment-1223887915

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/186139919-260688cd-f5e3-428e-a091-ab4f6a3f1a48.png)
我在stackoverflow看到了相关问题，我先设置下--no-stash  ， 看是否还会出现
