### ISSUE TITLE
[Bug report] 官方文档出现异常

### ISSUE THREAD

**Issue by CasualMing** [Zhengqbbb/cz-git#66]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```shell
无
```

#### Concise Description
官方文档 显示出现问题
![image](https://user-images.githubusercontent.com/40878104/192226266-7b925b55-a32e-42bd-9868-92f7bc27b451.png)

**Comment by Zhengqbbb** [comment]
感谢提醒 🤗
已修复于：
https://github.com/Zhengqbbb/cz-git/commit/1d991a6ceb413fb73fe3e5bb296d334373ad115b

**Comment by Zhengqbbb** [comment]
Thx your report ~ 🤗
U can use the link on a new notrace browser window to check the bug fixed：
```
https://cz-git.qbb.sh/zh/recipes/default-scope.html
```
