### ISSUE TITLE
Rule warning level not respected

### ISSUE THREAD

**Issue by JoaoEdu93** [Zhengqbbb/cz-git#71]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 19.79 GB / 31.89 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    commitizen: ^4.2.5 => 4.2.5
    cz-git: ^1.3.11 => 1.3.11
```

#### Description
In the file "commitlint.config.js" I have the rule "header-max-length" with the value 52 and with level 1 (warning).
When writing a header that exceeds 52 characters, it gives an error and won't let you proceed.

#### Expected behavior
It should display a warning message saying that the character limit has been exceeded, but it should let you proceed.

#### Screenshots
![image](https://user-images.githubusercontent.com/11159063/196057808-0d3a5bde-46b8-4d94-9a70-9b59832fb758.png)

**Comment by JoaoEdu93** [comment]
Thank you very much.
I've tried it out and it seems good. 👍

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.3.12)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. Thanks for you work! 🎉
