### ISSUE TITLE
[Feature Request] change  key bindings

### ISSUE THREAD

**Issue by fanxiao92** [Zhengqbbb/cz-git#74]
### 💭 Describe the feature

Is there a settings files so I can change  key bindings?
like c-n chang to  c-j , c-p change to c-k

**Comment by Zhengqbbb** [comment]
> ### 💭 Describe the feature
> Is there a settings files so I can change key bindings? like c-n chang to c-j , c-p change to c-k

What step you want to change  key and expect behavior ?

**Comment by Zhengqbbb** [comment]
Current use keyboard have <kbd>Tab</kbd> <kbd>Enter</kbd>  <kbd>⇧</kbd> <kbd>⇩</kbd>  <kbd>⇦</kbd>  <kbd>⇨</kbd> key.

If u would to use keyboard word to using in Pre or Next item.
IMHO. **I will say no**. it will affect search.
if u have other questions welcome to reopen ISSUE.
