### ISSUE TITLE
[Bug report] 默认配置下 emoji不能正确显示，只显示字符，比如 `:bug:`

### ISSUE THREAD

**Issue by Mrcxt** [Zhengqbbb/cz-git#77]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```shell
M1 macbook pro
```

#### Concise Description
默认配置下，设置`useEmoji:true`，提交commit时带入的emoji无法正确解析为emoji，而是显示为字符，如`:bug:`
<img width="271" alt="image" src="https://user-images.githubusercontent.com/16064831/201897299-28a1bf1c-33f1-4922-8af9-1aac42e15b20.png">

**Comment by Zhengqbbb** [comment]
什么平台？

**Comment by Mrcxt** [comment]
> 什么平台？ gitee || github || gitlab
> 
> `:bug:` 所代表的含义是 emoji所代表的 unicode [shortcode](https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md#animal-bug) 根据代码平台决定是否支持显示.
> 
> shortcode字符在 **命令行显示** 和 **代码平台**中的通用性是最好的，但是如果平台不支持的话，**将对应的 emoji 从字符改为 emoji 即可**。
> 
> e.g: [emoji 模版](https://cz-git.qbb.sh/zh/config/#emoji-%E6%A8%A1%E6%9D%BF)
> 
> ```diff
> types: [
> -      { value: "feat", name: "feat:     ✨  A new feature", emoji: ":sparkles:" },
> +      { value: "feat", name: "feat:     ✨  A new feature", emoji: "✨" },
> -      { value: "fix", name: "fix:      🐛  A bug fix", emoji: ":bug:" },
> +      { value: "fix", name: "fix:      🐛  A bug fix", emoji: "🐛" },
> -      { value: "docs", name: "docs:     📝  Documentation only changes", emoji: ":memo:" },
> +      { value: "docs", name: "docs:     📝  Documentation only changes", emoji: "📝" },
> -      { value: "chore", name: "chore:    🔨  Other changes that don't modify src or test files", emoji: ":hammer:" },
> +      { value: "chore", name: "chore:    🔨  Other changes that don't modify src or test files", emoji: "🔨" },
>       ...
>     ],
> ```
> 
> ref:
> 
> * [[Ask For Help] the emojis are not showing in the CLI. #49 (comment)](https://github.com/Zhengqbbb/cz-git/issues/49#issuecomment-1185696173)
> * [终端无法显示Emoji符号](https://cz-git.qbb.sh/zh/faq/#%E7%BB%88%E7%AB%AF%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BAemoji%E7%AC%A6%E5%8F%B7)

阿里云的cudeup平台，比较冷门。不过在vscode终端模式下查看 git log，commit记录上面的emoji也是只显示字符，不显示具体的emoji。目前我是按照自定义配置的方式将字符改成 emoji了。

**Comment by Zhengqbbb** [comment]
> 阿里云的cudeup平台，比较冷门。

应该是阿里云平台没有做 emoji shortcode 转 emoji/unicode

> 不过在vscode终端模式下查看 git log，commit记录上面的emoji也是只显示字符，不显示具体的emoji。

是的，一般要用命令行看的话可以 `pipe` 到 [emojify](https://github.com/mrowa44/emojify) parse emoji/unicode使用`git log | emojify`。不过目前看来你的终端等都是支持直接显示 emoji，那就不需要啦～

BTW：vscode 的 gitlens 是可以直接看的
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/40693636/202096996-09ab09a2-4670-4353-b295-d7d23dc705d5.png">
