### ISSUE TITLE
[Feature Request] add `confirmCommit` in `skipQuestions`

### ISSUE THREAD

**Issue by FatehAK** [Zhengqbbb/cz-git#86]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 966.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/13083_1670507240516/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/13083_1670507240516/bin/yarn
    npm: 9.1.3 - ~/Library/Caches/fnm_multishells/13083_1670507240516/bin/npm
    Watchman: 2022.11.28.00 - /opt/homebrew/bin/watchman
  npmPackages:
    czg: ^1.4.0 => 1.4.0
```

#### Concise Description
I'm trying to skip the `confirmCommit` step by adding it to the `skipQuestions` array in .commitlintrc.js

skipQuestions: ['body', 'breaking', 'footerPrefix', 'footer', 'confirmCommit'],

But doing so causes vim to open with an empty commit message

#### Expected behavior
Should be able to skip the `confirmCommit` step. A commit should be made directly if we reach the end of the czg steps.

#### Steps to reproduce
Add 'confirmCommit' to the skipQuestions array

**Comment by Zhengqbbb** [comment]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/40693636/206473424-6bbe387c-e668-4eaf-b62e-3dc2fb0dc4a2.png">
https://cz-git.qbb.sh/config/engineer#skipquestions
Not include `confirmCommit`

> But doing so causes vim to open with an empty commit message

**causes vim to open**. Is git hook `prepare-commit-msg` mode ?
<img width="710" alt="image" src="https://user-images.githubusercontent.com/40693636/206474063-cb27efbc-20b8-4d24-9dc5-a0cc3a184af7.png">

**Comment by FatehAK** [comment]
Yes but I tried it without prepare-commit-msg hook as well, by running czg directly but still I got

[info]>>>: Commit has been canceled.

**Comment by Zhengqbbb** [comment]
> Yes but I tried it without prepare-commit-msg hook as well, by running czg directly but still I got
> 
> [info]>>>: Commit has been canceled.

Not get `yes` default cancel.

I don't think this step should be skipped. This step is the last step to check the modification and repent. If you are sure, you can submit it directly. can you tell me what you need

**Comment by FatehAK** [comment]
Just thought of skipping that step can make committing faster. Since git shows the commit message at the end of committing anyway. If any changes in commit message (happens rarely) we could always amend the commit.

**Comment by Zhengqbbb** [comment]
ok if you  considered faster to use regular alias definitions, like `git czg :<alias>`
But if you use interactive, that means you really have to seriously write commit

**Comment by Zhengqbbb** [comment]
like https://github.com/Zhengqbbb/qbb.sh/blob/main/.czrc
https://cz-git.qbb.sh/recipes/alias

**Comment by FatehAK** [comment]
Aliases won't work in my scenario since all commits in the repo are husky lint-staged driven. 

But I agree on the seriousness part in interactive mode, just thought to avoid an enter key press again if dev knows what they have typed.

**Comment by Zhengqbbb** [comment]
I have finished and released the next(⭐️1.4.1-beta.1⭐️) version, you can use it first
 `npm install -D czg@next` and `npm install -D cz-git@next`

I expect to merge main and release in the weekend, you can use it first, and give feedback in time if there is any problem.

![demo](https://user-images.githubusercontent.com/40693636/206507592-36f2ffcc-4296-43ab-8ae6-8e8e1215cde0.gif)

**Comment by FatehAK** [comment]
Thank you. Will check and revert back in a bit.

**Comment by FatehAK** [comment]
Just tested it is working well. Also, noticed that the colorization is lost for the commit summary printed at the end when `confirmCommit` is added to skipQuestions.

-> `confirmCommit` added to skipQuestions
![Screen Shot 2022-12-09 at 12 46 53 AM](https://user-images.githubusercontent.com/34565559/206549033-c5e5783d-3d07-4e59-a5d9-317ad2998f1e.png)

-> `confirmCommit` not added to skipQuestions
![Screen Shot 2022-12-09 at 12 51 51 AM](https://user-images.githubusercontent.com/34565559/206549227-867f2842-2e2c-4091-b72e-75f7cacb5b11.png)

**Comment by FatehAK** [comment]
It is working great! I'd like to make one more suggestion, the emoji in the commit summary is printed like:

build: :sparkles: Upgrade pnpm

It would be great if it printed like this instead:

build: ✨ Upgrade pnpm

I feel having the emoji rendered makes it much easier to quickly glance over the commit summary.

**Comment by Zhengqbbb** [comment]
This involves the need to abbreviate emoji to emoji/unicode
1. **Compatibility** emoji/unicode requires terminal support, otherwise the box will be displayed
2. Not all platforms support emoji abbreviations, I do not only serve (github users)
3. There is also the question of whether to periodically synchronize the abbreviations
4. The most important thing is the **size**. Adding parse will double the size for me, which I cannot accept

Of course there are ways if you want to display:
1. Make sure your team Terminal supports displaying emoji/unicode
2. Change the emoji in types from abbreviation to direct emoji/unicode
``` diff
types: [
- { value: 'feat', name: 'feat: A new feature', emoji: ':sparkles:' },
+ { value: 'feat', name: 'feat: A new feature', emoji: '✨' },
]
```

https://cz-git.qbb.sh/config/show#types

**Comment by FatehAK** [comment]
Makes sense @Zhengqbbb didn't think of those scenarios. There are no other issues, you can merge the code when you get time. Thanks for helping out!

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.4.1)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. Thanks for you work! 🎉
