### ISSUE TITLE
Could not resolve cz-git. Cannot find module 'cz-git'.

### ISSUE THREAD

**Issue by xbzhang2020** [Zhengqbbb/cz-git#90]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.13 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
    Yarn: 3.3.1 - ~/.nvm/versions/node/v16.6.1/bin/yarn
    npm: 7.20.3 - ~/.nvm/versions/node/v16.6.1/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  npmGlobalPackages:
    commitizen: 4.2.6
```

#### Concise Description
My package manager is `yarn@3.3.1` which doesn't generate a `node_modules` directory. So I couldn't add `config` like this:
```json
{
  "scripts": {

  },
  "config": {
    "commitizen": {
      "path": "node_modules/cz-git"
    }
  }
}
```
When I tried modifying `"path": "node_modules/cz-git"` to `"path": "cz-git"`, I encountered an error:
```
Could not resolve cz-git. Cannot find module 'cz-git'
```
However, the way is OK in [git-cz](https://github.com/streamich/git-cz). Does `cz-git` support [Yarn Berry](https://github.com/yarnpkg/berry)? How to add `config` in this case?

#### Expected behavior
I could use `cz-git` in Yarn Berry.
#### Screenshots or Screen Recording(if possible)
<img width="1140" alt="截屏2023-01-05 10 20 17" src="https://user-images.githubusercontent.com/39360445/210689631-14670f1d-6fbb-4f63-bc5a-b32df1e59c20.png">
<img width="957" alt="截屏2023-01-05 10 23 57" src="https://user-images.githubusercontent.com/39360445/210689653-6a69fa74-f38a-4283-9e2d-ab22943433c4.png">

**Comment by Zhengqbbb** [comment]
> which doesn't generate a node_modules directory.
it causes the commitizen CLI cannot find the cz-git adapter. This is out of my control.

You can have try my solution:
1. Install cz-git globally
2. Or try **`czg`**. alternative to commitizen CLI + cz-git  https://cz-git.qbb.sh/cli/

I'll be testing yarn3 later today

**Comment by Zhengqbbb** [comment]
I made an example repo. Hope it will be helpful to your project. If you have any other questions, can come back to discuss
https://github.com/Zhengqbbb/czgit-playground/tree/czg-yarn-v3

**Comment by xbzhang2020** [comment]
> > which doesn't generate a node_modules directory.
> 
> It causes the commitizen CLI cannot find the `cz-git` adapter. The process is commitizen CLI behavior, not controlled by `cz-git`

I think it might not be commitizen's fault.
After reading commitizen's code, I fond that commitizen uses `require.reslove()` to resolve the path of a adaptor. 

Then I ran a demo.

<img width="1379" alt="截屏2023-01-05 20 36 05" src="https://user-images.githubusercontent.com/39360445/210781783-b60145cc-f414-4a31-8bc1-8299cf95d613.png">

Oops!

However, I tested `git-cz`, it ran successfully.

<img width="1367" alt="截屏2023-01-05 20 35 43" src="https://user-images.githubusercontent.com/39360445/210782238-dfcad44d-8bf5-45b1-83f9-0cea30d177b6.png">

Why?

**Comment by Zhengqbbb** [comment]
**I guess you downloaded `git-cz` globally** so node can find it layer by layer.Run the command copy please:

```sh
npx envinfo --system --binaries     \
    --npmPackages cz-git            \
    --npmPackages commitizen        \
    --npmPackages czg               \
    --npmPackages git-cz            \
    --npmGlobalPackages cz-git      \
    --npmGlobalPackages commitizen  \
    --npmGlobalPackages czg         \
    --npmGlobalPackages git-cz
```

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/40693636/210792925-7e7c1038-eeb7-4f1b-9901-a1d39e321f6f.png">

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/40693636/210793747-42d6fddd-74f4-4d41-bbca-0d63776b51bd.png">

**Comment by Zhengqbbb** [comment]
Btw `require.reslove()` is a package that can be downloaded globally. Use this to enable global mode.
The essence is that you need to pass my adapter bin path to commitizen CLI.
https://cz-git.qbb.sh/guide/#as-global-use.


`echo '{ "path": "cz-git" }' > ~/.czrc` = `require.reslove()`

**Comment by xbzhang2020** [comment]
Yeah, I get it. I have no other questions. Thanks!
