### ISSUE TITLE
[Feature Request] 为 czg ai 这个功能点赞！！！

### ISSUE THREAD

**Issue by danyow** [Zhengqbbb/cz-git#94]
### 💭 Describe the feature

`czg ai` 这个功能非常好用，但是我希望更加好用

我先说说我的诉求

我希望我使用了 ai 之后还能继续关联一下问题，也就是去关联 issuse。

### 💡 Proposed Solution

我想到了两个方法 
1. 是在提问环节生成ai前加多个提问，但我觉得不合理
  <img width="588" alt="image" src="https://user-images.githubusercontent.com/15705152/221342624-d8f0c8c7-d1a4-459b-8f35-5e3cda2ffffd.png">  

2. 就是 `formatMessageCB` 格式化回调的时候，我自己增加代码去添加问题和得到回答
  <img width="546" alt="image" src="https://user-images.githubusercontent.com/15705152/221342771-6d5d520a-0597-40f0-acdd-081ec15b27c5.png">  
相对来说我觉得合理一点 并且再不修改源码的情况 加入了更高的客制化

**Comment by Zhengqbbb** [comment]
感谢你的支持 😁
- 关于生成之后的设计，我应该还是会遵循普通模式结合补全的用法

<img width="958" alt="image" src="https://user-images.githubusercontent.com/40693636/221453081-1ae53b74-c7da-4d4b-bd22-1b8e5c4197f6.png">

- 关于 formatCB 我会参考参考尝试

- 但目前我希望这个版本先稳定一段时间，预计下下周的周末完成新一的一版<sup>应该可以 :)</sup>

再一次感谢

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.6.0)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are any issues. Thanks u support! 🎉

@danyow  久等 🌟(v1.6.0)🌟 已经发布，支持在确认的时候进行修改或补充上下文 <kbd>m</kbd> (modify)，感谢你的支持 ~

https://user-images.githubusercontent.com/40693636/224512155-c040e382-d71d-4914-a113-3bdf1c27cb80.mp4
