### ISSUE TITLE
可以加入代理配置的选项吗

### ISSUE THREAD

**Issue by harwinvoid** [Zhengqbbb/cz-git#98]
### 💭 Describe the feature

![image](https://user-images.githubusercontent.com/12931494/222900328-22e79ac7-82d1-4f0e-ac23-ce88172008ba.png)
现在open api 被墙了，node好像默认不走 clash 代理，希望可以加个代理配置的选项。

**Comment by Zhengqbbb** [comment]
0.0  是的被墙了我今天刚发的版本
做成配置是吧  我这几天安排
目前的话你可以用命令设置
e.g:
```sh
export https_proxy=http://127.0.0.1:1088 http_proxy=http://127.0.0.1:1088 all_proxy=socks5://127.0.0.1:1088
```

ps： 可能是我把这段 export 做了命令所以习惯了

**Comment by Zhengqbbb** [comment]
ps 小技巧: 可以把proxy做成自己的命令，添加到 .zshrc 或 .bashrc

```sh
qb-proxy() {
	export https_proxy=http://127.0.0.1:1088 http_proxy=http://127.0.0.1:1088 all_proxy=socks5://127.0.0.1:1088 && curl google.com
}
```

出现 301 就说明代理成功了
<img width="885" alt="image" src="https://user-images.githubusercontent.com/40693636/222901302-eb7117ae-c665-492d-917e-9b5b89f05836.png">

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.5.3)🌟 is  released. Should be resolve this ISSUE request.

e.g:
- `npx czg@latest --api-proxy="socks5://127.0.0.1:1088"`
- `npx czg@latest --api-proxy="http://127.0.0.1:1088"`

连夜肝出来了，试试看吧，如果有问题请告诉我
https://user-images.githubusercontent.com/40693636/222927192-fbca7a63-01eb-4427-8f45-5fe2547f1baf.mov

**Comment by harwinvoid** [comment]
感谢🙏
