### ISSUE TITLE
The current version of cz-git@1.5.1 does not support ES modules.

### ISSUE THREAD

**Issue by h7ml** [Zhengqbbb/cz-git#99]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 4.94 GB / 15.73 GB
  Binaries:
    Node: 16.19.1 - ~\AppData\Local\Volta\tools\image\node\16.19.1\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
    npm: 8.19.3 - ~\AppData\Local\Volta\tools\image\node\16.19.1\npm.CMD
  npmPackages:
    cz-git: ^1.5.1 => 1.5.1
```

### 🔎 Description

![image](https://user-images.githubusercontent.com/55233292/222903427-ce7cdf2f-36d2-410a-b664-ba0718202286.png)

**Comment by Zhengqbbb** [comment]
.commitlintrc.cjs

**Comment by Zhengqbbb** [comment]
https://github.com/Zhengqbbb/cz-git/discussions/79

**Comment by h7ml** [comment]
> .commitlintrc.cjs

Thank you very much. This solved my problem.

**Comment by Zhengqbbb** [comment]
Hi there 👋
The latest version 🌟(v1.11.0)🌟 released and supported ESM configure loading.
Docs Link: https://cz-git.qbb.sh/config/
💪 Please have a try. 👀 Let me know if there are still any issues. 🎉
